
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Countdowns` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Countdowns
 * 
 */
export type CountdownsModel = runtime.Types.Result.DefaultSelection<Prisma.$CountdownsPayload>

export type AggregateCountdowns = {
  _count: CountdownsCountAggregateOutputType | null
  _avg: CountdownsAvgAggregateOutputType | null
  _sum: CountdownsSumAggregateOutputType | null
  _min: CountdownsMinAggregateOutputType | null
  _max: CountdownsMaxAggregateOutputType | null
}

export type CountdownsAvgAggregateOutputType = {
  countdown: number | null
}

export type CountdownsSumAggregateOutputType = {
  countdown: number | null
}

export type CountdownsMinAggregateOutputType = {
  id: string | null
  countdown: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CountdownsMaxAggregateOutputType = {
  id: string | null
  countdown: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CountdownsCountAggregateOutputType = {
  id: number
  countdown: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CountdownsAvgAggregateInputType = {
  countdown?: true
}

export type CountdownsSumAggregateInputType = {
  countdown?: true
}

export type CountdownsMinAggregateInputType = {
  id?: true
  countdown?: true
  createdAt?: true
  updatedAt?: true
}

export type CountdownsMaxAggregateInputType = {
  id?: true
  countdown?: true
  createdAt?: true
  updatedAt?: true
}

export type CountdownsCountAggregateInputType = {
  id?: true
  countdown?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CountdownsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Countdowns to aggregate.
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countdowns to fetch.
   */
  orderBy?: Prisma.CountdownsOrderByWithRelationInput | Prisma.CountdownsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CountdownsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countdowns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countdowns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Countdowns
  **/
  _count?: true | CountdownsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CountdownsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CountdownsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CountdownsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CountdownsMaxAggregateInputType
}

export type GetCountdownsAggregateType<T extends CountdownsAggregateArgs> = {
      [P in keyof T & keyof AggregateCountdowns]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCountdowns[P]>
    : Prisma.GetScalarType<T[P], AggregateCountdowns[P]>
}




export type CountdownsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CountdownsWhereInput
  orderBy?: Prisma.CountdownsOrderByWithAggregationInput | Prisma.CountdownsOrderByWithAggregationInput[]
  by: Prisma.CountdownsScalarFieldEnum[] | Prisma.CountdownsScalarFieldEnum
  having?: Prisma.CountdownsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CountdownsCountAggregateInputType | true
  _avg?: CountdownsAvgAggregateInputType
  _sum?: CountdownsSumAggregateInputType
  _min?: CountdownsMinAggregateInputType
  _max?: CountdownsMaxAggregateInputType
}

export type CountdownsGroupByOutputType = {
  id: string
  countdown: number
  createdAt: Date
  updatedAt: Date
  _count: CountdownsCountAggregateOutputType | null
  _avg: CountdownsAvgAggregateOutputType | null
  _sum: CountdownsSumAggregateOutputType | null
  _min: CountdownsMinAggregateOutputType | null
  _max: CountdownsMaxAggregateOutputType | null
}

export type GetCountdownsGroupByPayload<T extends CountdownsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CountdownsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CountdownsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CountdownsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CountdownsGroupByOutputType[P]>
      }
    >
  >



export type CountdownsWhereInput = {
  AND?: Prisma.CountdownsWhereInput | Prisma.CountdownsWhereInput[]
  OR?: Prisma.CountdownsWhereInput[]
  NOT?: Prisma.CountdownsWhereInput | Prisma.CountdownsWhereInput[]
  id?: Prisma.StringFilter<"Countdowns"> | string
  countdown?: Prisma.IntFilter<"Countdowns"> | number
  createdAt?: Prisma.DateTimeFilter<"Countdowns"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Countdowns"> | Date | string
}

export type CountdownsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  countdown?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountdownsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CountdownsWhereInput | Prisma.CountdownsWhereInput[]
  OR?: Prisma.CountdownsWhereInput[]
  NOT?: Prisma.CountdownsWhereInput | Prisma.CountdownsWhereInput[]
  countdown?: Prisma.IntFilter<"Countdowns"> | number
  createdAt?: Prisma.DateTimeFilter<"Countdowns"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Countdowns"> | Date | string
}, "id">

export type CountdownsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  countdown?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CountdownsCountOrderByAggregateInput
  _avg?: Prisma.CountdownsAvgOrderByAggregateInput
  _max?: Prisma.CountdownsMaxOrderByAggregateInput
  _min?: Prisma.CountdownsMinOrderByAggregateInput
  _sum?: Prisma.CountdownsSumOrderByAggregateInput
}

export type CountdownsScalarWhereWithAggregatesInput = {
  AND?: Prisma.CountdownsScalarWhereWithAggregatesInput | Prisma.CountdownsScalarWhereWithAggregatesInput[]
  OR?: Prisma.CountdownsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CountdownsScalarWhereWithAggregatesInput | Prisma.CountdownsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Countdowns"> | string
  countdown?: Prisma.IntWithAggregatesFilter<"Countdowns"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Countdowns"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Countdowns"> | Date | string
}

export type CountdownsCreateInput = {
  id?: string
  countdown: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountdownsUncheckedCreateInput = {
  id?: string
  countdown: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountdownsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  countdown?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountdownsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  countdown?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountdownsCreateManyInput = {
  id?: string
  countdown: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CountdownsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  countdown?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountdownsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  countdown?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CountdownsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  countdown?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountdownsAvgOrderByAggregateInput = {
  countdown?: Prisma.SortOrder
}

export type CountdownsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  countdown?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountdownsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  countdown?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CountdownsSumOrderByAggregateInput = {
  countdown?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type CountdownsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  countdown?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["countdowns"]>

export type CountdownsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  countdown?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["countdowns"]>

export type CountdownsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  countdown?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["countdowns"]>

export type CountdownsSelectScalar = {
  id?: boolean
  countdown?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CountdownsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "countdown" | "createdAt" | "updatedAt", ExtArgs["result"]["countdowns"]>

export type $CountdownsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Countdowns"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    countdown: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["countdowns"]>
  composites: {}
}

export type CountdownsGetPayload<S extends boolean | null | undefined | CountdownsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CountdownsPayload, S>

export type CountdownsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CountdownsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CountdownsCountAggregateInputType | true
  }

export interface CountdownsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Countdowns'], meta: { name: 'Countdowns' } }
  /**
   * Find zero or one Countdowns that matches the filter.
   * @param {CountdownsFindUniqueArgs} args - Arguments to find a Countdowns
   * @example
   * // Get one Countdowns
   * const countdowns = await prisma.countdowns.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CountdownsFindUniqueArgs>(args: Prisma.SelectSubset<T, CountdownsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Countdowns that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CountdownsFindUniqueOrThrowArgs} args - Arguments to find a Countdowns
   * @example
   * // Get one Countdowns
   * const countdowns = await prisma.countdowns.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CountdownsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CountdownsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Countdowns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsFindFirstArgs} args - Arguments to find a Countdowns
   * @example
   * // Get one Countdowns
   * const countdowns = await prisma.countdowns.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CountdownsFindFirstArgs>(args?: Prisma.SelectSubset<T, CountdownsFindFirstArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Countdowns that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsFindFirstOrThrowArgs} args - Arguments to find a Countdowns
   * @example
   * // Get one Countdowns
   * const countdowns = await prisma.countdowns.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CountdownsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CountdownsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Countdowns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Countdowns
   * const countdowns = await prisma.countdowns.findMany()
   * 
   * // Get first 10 Countdowns
   * const countdowns = await prisma.countdowns.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const countdownsWithIdOnly = await prisma.countdowns.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CountdownsFindManyArgs>(args?: Prisma.SelectSubset<T, CountdownsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Countdowns.
   * @param {CountdownsCreateArgs} args - Arguments to create a Countdowns.
   * @example
   * // Create one Countdowns
   * const Countdowns = await prisma.countdowns.create({
   *   data: {
   *     // ... data to create a Countdowns
   *   }
   * })
   * 
   */
  create<T extends CountdownsCreateArgs>(args: Prisma.SelectSubset<T, CountdownsCreateArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Countdowns.
   * @param {CountdownsCreateManyArgs} args - Arguments to create many Countdowns.
   * @example
   * // Create many Countdowns
   * const countdowns = await prisma.countdowns.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CountdownsCreateManyArgs>(args?: Prisma.SelectSubset<T, CountdownsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Countdowns and returns the data saved in the database.
   * @param {CountdownsCreateManyAndReturnArgs} args - Arguments to create many Countdowns.
   * @example
   * // Create many Countdowns
   * const countdowns = await prisma.countdowns.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Countdowns and only return the `id`
   * const countdownsWithIdOnly = await prisma.countdowns.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CountdownsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CountdownsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Countdowns.
   * @param {CountdownsDeleteArgs} args - Arguments to delete one Countdowns.
   * @example
   * // Delete one Countdowns
   * const Countdowns = await prisma.countdowns.delete({
   *   where: {
   *     // ... filter to delete one Countdowns
   *   }
   * })
   * 
   */
  delete<T extends CountdownsDeleteArgs>(args: Prisma.SelectSubset<T, CountdownsDeleteArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Countdowns.
   * @param {CountdownsUpdateArgs} args - Arguments to update one Countdowns.
   * @example
   * // Update one Countdowns
   * const countdowns = await prisma.countdowns.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CountdownsUpdateArgs>(args: Prisma.SelectSubset<T, CountdownsUpdateArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Countdowns.
   * @param {CountdownsDeleteManyArgs} args - Arguments to filter Countdowns to delete.
   * @example
   * // Delete a few Countdowns
   * const { count } = await prisma.countdowns.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CountdownsDeleteManyArgs>(args?: Prisma.SelectSubset<T, CountdownsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Countdowns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Countdowns
   * const countdowns = await prisma.countdowns.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CountdownsUpdateManyArgs>(args: Prisma.SelectSubset<T, CountdownsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Countdowns and returns the data updated in the database.
   * @param {CountdownsUpdateManyAndReturnArgs} args - Arguments to update many Countdowns.
   * @example
   * // Update many Countdowns
   * const countdowns = await prisma.countdowns.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Countdowns and only return the `id`
   * const countdownsWithIdOnly = await prisma.countdowns.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CountdownsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CountdownsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Countdowns.
   * @param {CountdownsUpsertArgs} args - Arguments to update or create a Countdowns.
   * @example
   * // Update or create a Countdowns
   * const countdowns = await prisma.countdowns.upsert({
   *   create: {
   *     // ... data to create a Countdowns
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Countdowns we want to update
   *   }
   * })
   */
  upsert<T extends CountdownsUpsertArgs>(args: Prisma.SelectSubset<T, CountdownsUpsertArgs<ExtArgs>>): Prisma.Prisma__CountdownsClient<runtime.Types.Result.GetResult<Prisma.$CountdownsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Countdowns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsCountArgs} args - Arguments to filter Countdowns to count.
   * @example
   * // Count the number of Countdowns
   * const count = await prisma.countdowns.count({
   *   where: {
   *     // ... the filter for the Countdowns we want to count
   *   }
   * })
  **/
  count<T extends CountdownsCountArgs>(
    args?: Prisma.Subset<T, CountdownsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CountdownsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Countdowns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CountdownsAggregateArgs>(args: Prisma.Subset<T, CountdownsAggregateArgs>): Prisma.PrismaPromise<GetCountdownsAggregateType<T>>

  /**
   * Group by Countdowns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CountdownsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CountdownsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CountdownsGroupByArgs['orderBy'] }
      : { orderBy?: CountdownsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CountdownsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCountdownsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Countdowns model
 */
readonly fields: CountdownsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Countdowns.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CountdownsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Countdowns model
 */
export interface CountdownsFieldRefs {
  readonly id: Prisma.FieldRef<"Countdowns", 'String'>
  readonly countdown: Prisma.FieldRef<"Countdowns", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Countdowns", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Countdowns", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Countdowns findUnique
 */
export type CountdownsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * Filter, which Countdowns to fetch.
   */
  where: Prisma.CountdownsWhereUniqueInput
}

/**
 * Countdowns findUniqueOrThrow
 */
export type CountdownsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * Filter, which Countdowns to fetch.
   */
  where: Prisma.CountdownsWhereUniqueInput
}

/**
 * Countdowns findFirst
 */
export type CountdownsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * Filter, which Countdowns to fetch.
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countdowns to fetch.
   */
  orderBy?: Prisma.CountdownsOrderByWithRelationInput | Prisma.CountdownsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Countdowns.
   */
  cursor?: Prisma.CountdownsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countdowns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countdowns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Countdowns.
   */
  distinct?: Prisma.CountdownsScalarFieldEnum | Prisma.CountdownsScalarFieldEnum[]
}

/**
 * Countdowns findFirstOrThrow
 */
export type CountdownsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * Filter, which Countdowns to fetch.
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countdowns to fetch.
   */
  orderBy?: Prisma.CountdownsOrderByWithRelationInput | Prisma.CountdownsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Countdowns.
   */
  cursor?: Prisma.CountdownsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countdowns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countdowns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Countdowns.
   */
  distinct?: Prisma.CountdownsScalarFieldEnum | Prisma.CountdownsScalarFieldEnum[]
}

/**
 * Countdowns findMany
 */
export type CountdownsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * Filter, which Countdowns to fetch.
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Countdowns to fetch.
   */
  orderBy?: Prisma.CountdownsOrderByWithRelationInput | Prisma.CountdownsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Countdowns.
   */
  cursor?: Prisma.CountdownsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Countdowns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Countdowns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Countdowns.
   */
  distinct?: Prisma.CountdownsScalarFieldEnum | Prisma.CountdownsScalarFieldEnum[]
}

/**
 * Countdowns create
 */
export type CountdownsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * The data needed to create a Countdowns.
   */
  data: Prisma.XOR<Prisma.CountdownsCreateInput, Prisma.CountdownsUncheckedCreateInput>
}

/**
 * Countdowns createMany
 */
export type CountdownsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Countdowns.
   */
  data: Prisma.CountdownsCreateManyInput | Prisma.CountdownsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Countdowns createManyAndReturn
 */
export type CountdownsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * The data used to create many Countdowns.
   */
  data: Prisma.CountdownsCreateManyInput | Prisma.CountdownsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Countdowns update
 */
export type CountdownsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * The data needed to update a Countdowns.
   */
  data: Prisma.XOR<Prisma.CountdownsUpdateInput, Prisma.CountdownsUncheckedUpdateInput>
  /**
   * Choose, which Countdowns to update.
   */
  where: Prisma.CountdownsWhereUniqueInput
}

/**
 * Countdowns updateMany
 */
export type CountdownsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Countdowns.
   */
  data: Prisma.XOR<Prisma.CountdownsUpdateManyMutationInput, Prisma.CountdownsUncheckedUpdateManyInput>
  /**
   * Filter which Countdowns to update
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * Limit how many Countdowns to update.
   */
  limit?: number
}

/**
 * Countdowns updateManyAndReturn
 */
export type CountdownsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * The data used to update Countdowns.
   */
  data: Prisma.XOR<Prisma.CountdownsUpdateManyMutationInput, Prisma.CountdownsUncheckedUpdateManyInput>
  /**
   * Filter which Countdowns to update
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * Limit how many Countdowns to update.
   */
  limit?: number
}

/**
 * Countdowns upsert
 */
export type CountdownsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * The filter to search for the Countdowns to update in case it exists.
   */
  where: Prisma.CountdownsWhereUniqueInput
  /**
   * In case the Countdowns found by the `where` argument doesn't exist, create a new Countdowns with this data.
   */
  create: Prisma.XOR<Prisma.CountdownsCreateInput, Prisma.CountdownsUncheckedCreateInput>
  /**
   * In case the Countdowns was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CountdownsUpdateInput, Prisma.CountdownsUncheckedUpdateInput>
}

/**
 * Countdowns delete
 */
export type CountdownsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
  /**
   * Filter which Countdowns to delete.
   */
  where: Prisma.CountdownsWhereUniqueInput
}

/**
 * Countdowns deleteMany
 */
export type CountdownsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Countdowns to delete
   */
  where?: Prisma.CountdownsWhereInput
  /**
   * Limit how many Countdowns to delete.
   */
  limit?: number
}

/**
 * Countdowns without action
 */
export type CountdownsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Countdowns
   */
  select?: Prisma.CountdownsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Countdowns
   */
  omit?: Prisma.CountdownsOmit<ExtArgs> | null
}
