
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FilesOnProfiles` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FilesOnProfiles
 * 
 */
export type FilesOnProfilesModel = runtime.Types.Result.DefaultSelection<Prisma.$FilesOnProfilesPayload>

export type AggregateFilesOnProfiles = {
  _count: FilesOnProfilesCountAggregateOutputType | null
  _min: FilesOnProfilesMinAggregateOutputType | null
  _max: FilesOnProfilesMaxAggregateOutputType | null
}

export type FilesOnProfilesMinAggregateOutputType = {
  id: string | null
  fileImagePath: string | null
  profileId: string | null
}

export type FilesOnProfilesMaxAggregateOutputType = {
  id: string | null
  fileImagePath: string | null
  profileId: string | null
}

export type FilesOnProfilesCountAggregateOutputType = {
  id: number
  fileImagePath: number
  profileId: number
  _all: number
}


export type FilesOnProfilesMinAggregateInputType = {
  id?: true
  fileImagePath?: true
  profileId?: true
}

export type FilesOnProfilesMaxAggregateInputType = {
  id?: true
  fileImagePath?: true
  profileId?: true
}

export type FilesOnProfilesCountAggregateInputType = {
  id?: true
  fileImagePath?: true
  profileId?: true
  _all?: true
}

export type FilesOnProfilesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FilesOnProfiles to aggregate.
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilesOnProfiles to fetch.
   */
  orderBy?: Prisma.FilesOnProfilesOrderByWithRelationInput | Prisma.FilesOnProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FilesOnProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilesOnProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilesOnProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FilesOnProfiles
  **/
  _count?: true | FilesOnProfilesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FilesOnProfilesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FilesOnProfilesMaxAggregateInputType
}

export type GetFilesOnProfilesAggregateType<T extends FilesOnProfilesAggregateArgs> = {
      [P in keyof T & keyof AggregateFilesOnProfiles]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFilesOnProfiles[P]>
    : Prisma.GetScalarType<T[P], AggregateFilesOnProfiles[P]>
}




export type FilesOnProfilesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilesOnProfilesWhereInput
  orderBy?: Prisma.FilesOnProfilesOrderByWithAggregationInput | Prisma.FilesOnProfilesOrderByWithAggregationInput[]
  by: Prisma.FilesOnProfilesScalarFieldEnum[] | Prisma.FilesOnProfilesScalarFieldEnum
  having?: Prisma.FilesOnProfilesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FilesOnProfilesCountAggregateInputType | true
  _min?: FilesOnProfilesMinAggregateInputType
  _max?: FilesOnProfilesMaxAggregateInputType
}

export type FilesOnProfilesGroupByOutputType = {
  id: string
  fileImagePath: string
  profileId: string
  _count: FilesOnProfilesCountAggregateOutputType | null
  _min: FilesOnProfilesMinAggregateOutputType | null
  _max: FilesOnProfilesMaxAggregateOutputType | null
}

export type GetFilesOnProfilesGroupByPayload<T extends FilesOnProfilesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FilesOnProfilesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FilesOnProfilesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FilesOnProfilesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FilesOnProfilesGroupByOutputType[P]>
      }
    >
  >



export type FilesOnProfilesWhereInput = {
  AND?: Prisma.FilesOnProfilesWhereInput | Prisma.FilesOnProfilesWhereInput[]
  OR?: Prisma.FilesOnProfilesWhereInput[]
  NOT?: Prisma.FilesOnProfilesWhereInput | Prisma.FilesOnProfilesWhereInput[]
  id?: Prisma.StringFilter<"FilesOnProfiles"> | string
  fileImagePath?: Prisma.StringFilter<"FilesOnProfiles"> | string
  profileId?: Prisma.StringFilter<"FilesOnProfiles"> | string
  filePath?: Prisma.XOR<Prisma.FilePathScalarRelationFilter, Prisma.FilePathWhereInput>
  profile?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.ProfilesWhereInput>
}

export type FilesOnProfilesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  filePath?: Prisma.FilePathOrderByWithRelationInput
  profile?: Prisma.ProfilesOrderByWithRelationInput
}

export type FilesOnProfilesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  profileId?: string
  fileImagePath_profileId?: Prisma.FilesOnProfilesFileImagePathProfileIdCompoundUniqueInput
  AND?: Prisma.FilesOnProfilesWhereInput | Prisma.FilesOnProfilesWhereInput[]
  OR?: Prisma.FilesOnProfilesWhereInput[]
  NOT?: Prisma.FilesOnProfilesWhereInput | Prisma.FilesOnProfilesWhereInput[]
  fileImagePath?: Prisma.StringFilter<"FilesOnProfiles"> | string
  filePath?: Prisma.XOR<Prisma.FilePathScalarRelationFilter, Prisma.FilePathWhereInput>
  profile?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.ProfilesWhereInput>
}, "id" | "profileId" | "fileImagePath_profileId">

export type FilesOnProfilesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  _count?: Prisma.FilesOnProfilesCountOrderByAggregateInput
  _max?: Prisma.FilesOnProfilesMaxOrderByAggregateInput
  _min?: Prisma.FilesOnProfilesMinOrderByAggregateInput
}

export type FilesOnProfilesScalarWhereWithAggregatesInput = {
  AND?: Prisma.FilesOnProfilesScalarWhereWithAggregatesInput | Prisma.FilesOnProfilesScalarWhereWithAggregatesInput[]
  OR?: Prisma.FilesOnProfilesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FilesOnProfilesScalarWhereWithAggregatesInput | Prisma.FilesOnProfilesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FilesOnProfiles"> | string
  fileImagePath?: Prisma.StringWithAggregatesFilter<"FilesOnProfiles"> | string
  profileId?: Prisma.StringWithAggregatesFilter<"FilesOnProfiles"> | string
}

export type FilesOnProfilesCreateInput = {
  id?: string
  filePath: Prisma.FilePathCreateNestedOneWithoutAvatarFilesInput
  profile: Prisma.ProfilesCreateNestedOneWithoutAvatarPathInput
}

export type FilesOnProfilesUncheckedCreateInput = {
  id?: string
  fileImagePath: string
  profileId: string
}

export type FilesOnProfilesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.FilePathUpdateOneRequiredWithoutAvatarFilesNestedInput
  profile?: Prisma.ProfilesUpdateOneRequiredWithoutAvatarPathNestedInput
}

export type FilesOnProfilesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilesOnProfilesCreateManyInput = {
  id?: string
  fileImagePath: string
  profileId: string
}

export type FilesOnProfilesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilesOnProfilesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilesOnProfilesListRelationFilter = {
  every?: Prisma.FilesOnProfilesWhereInput
  some?: Prisma.FilesOnProfilesWhereInput
  none?: Prisma.FilesOnProfilesWhereInput
}

export type FilesOnProfilesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FilesOnProfilesFileImagePathProfileIdCompoundUniqueInput = {
  fileImagePath: string
  profileId: string
}

export type FilesOnProfilesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
}

export type FilesOnProfilesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
}

export type FilesOnProfilesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
}

export type FilesOnProfilesNullableScalarRelationFilter = {
  is?: Prisma.FilesOnProfilesWhereInput | null
  isNot?: Prisma.FilesOnProfilesWhereInput | null
}

export type FilesOnProfilesCreateNestedManyWithoutFilePathInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput> | Prisma.FilesOnProfilesCreateWithoutFilePathInput[] | Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput | Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput[]
  createMany?: Prisma.FilesOnProfilesCreateManyFilePathInputEnvelope
  connect?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
}

export type FilesOnProfilesUncheckedCreateNestedManyWithoutFilePathInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput> | Prisma.FilesOnProfilesCreateWithoutFilePathInput[] | Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput | Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput[]
  createMany?: Prisma.FilesOnProfilesCreateManyFilePathInputEnvelope
  connect?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
}

export type FilesOnProfilesUpdateManyWithoutFilePathNestedInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput> | Prisma.FilesOnProfilesCreateWithoutFilePathInput[] | Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput | Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput[]
  upsert?: Prisma.FilesOnProfilesUpsertWithWhereUniqueWithoutFilePathInput | Prisma.FilesOnProfilesUpsertWithWhereUniqueWithoutFilePathInput[]
  createMany?: Prisma.FilesOnProfilesCreateManyFilePathInputEnvelope
  set?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  disconnect?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  delete?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  connect?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  update?: Prisma.FilesOnProfilesUpdateWithWhereUniqueWithoutFilePathInput | Prisma.FilesOnProfilesUpdateWithWhereUniqueWithoutFilePathInput[]
  updateMany?: Prisma.FilesOnProfilesUpdateManyWithWhereWithoutFilePathInput | Prisma.FilesOnProfilesUpdateManyWithWhereWithoutFilePathInput[]
  deleteMany?: Prisma.FilesOnProfilesScalarWhereInput | Prisma.FilesOnProfilesScalarWhereInput[]
}

export type FilesOnProfilesUncheckedUpdateManyWithoutFilePathNestedInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput> | Prisma.FilesOnProfilesCreateWithoutFilePathInput[] | Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput | Prisma.FilesOnProfilesCreateOrConnectWithoutFilePathInput[]
  upsert?: Prisma.FilesOnProfilesUpsertWithWhereUniqueWithoutFilePathInput | Prisma.FilesOnProfilesUpsertWithWhereUniqueWithoutFilePathInput[]
  createMany?: Prisma.FilesOnProfilesCreateManyFilePathInputEnvelope
  set?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  disconnect?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  delete?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  connect?: Prisma.FilesOnProfilesWhereUniqueInput | Prisma.FilesOnProfilesWhereUniqueInput[]
  update?: Prisma.FilesOnProfilesUpdateWithWhereUniqueWithoutFilePathInput | Prisma.FilesOnProfilesUpdateWithWhereUniqueWithoutFilePathInput[]
  updateMany?: Prisma.FilesOnProfilesUpdateManyWithWhereWithoutFilePathInput | Prisma.FilesOnProfilesUpdateManyWithWhereWithoutFilePathInput[]
  deleteMany?: Prisma.FilesOnProfilesScalarWhereInput | Prisma.FilesOnProfilesScalarWhereInput[]
}

export type FilesOnProfilesCreateNestedOneWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutProfileInput
  connect?: Prisma.FilesOnProfilesWhereUniqueInput
}

export type FilesOnProfilesUncheckedCreateNestedOneWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutProfileInput
  connect?: Prisma.FilesOnProfilesWhereUniqueInput
}

export type FilesOnProfilesUpdateOneWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutProfileInput
  upsert?: Prisma.FilesOnProfilesUpsertWithoutProfileInput
  disconnect?: Prisma.FilesOnProfilesWhereInput | boolean
  delete?: Prisma.FilesOnProfilesWhereInput | boolean
  connect?: Prisma.FilesOnProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilesOnProfilesUpdateToOneWithWhereWithoutProfileInput, Prisma.FilesOnProfilesUpdateWithoutProfileInput>, Prisma.FilesOnProfilesUncheckedUpdateWithoutProfileInput>
}

export type FilesOnProfilesUncheckedUpdateOneWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedCreateWithoutProfileInput>
  connectOrCreate?: Prisma.FilesOnProfilesCreateOrConnectWithoutProfileInput
  upsert?: Prisma.FilesOnProfilesUpsertWithoutProfileInput
  disconnect?: Prisma.FilesOnProfilesWhereInput | boolean
  delete?: Prisma.FilesOnProfilesWhereInput | boolean
  connect?: Prisma.FilesOnProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilesOnProfilesUpdateToOneWithWhereWithoutProfileInput, Prisma.FilesOnProfilesUpdateWithoutProfileInput>, Prisma.FilesOnProfilesUncheckedUpdateWithoutProfileInput>
}

export type FilesOnProfilesCreateWithoutFilePathInput = {
  id?: string
  profile: Prisma.ProfilesCreateNestedOneWithoutAvatarPathInput
}

export type FilesOnProfilesUncheckedCreateWithoutFilePathInput = {
  id?: string
  profileId: string
}

export type FilesOnProfilesCreateOrConnectWithoutFilePathInput = {
  where: Prisma.FilesOnProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput>
}

export type FilesOnProfilesCreateManyFilePathInputEnvelope = {
  data: Prisma.FilesOnProfilesCreateManyFilePathInput | Prisma.FilesOnProfilesCreateManyFilePathInput[]
  skipDuplicates?: boolean
}

export type FilesOnProfilesUpsertWithWhereUniqueWithoutFilePathInput = {
  where: Prisma.FilesOnProfilesWhereUniqueInput
  update: Prisma.XOR<Prisma.FilesOnProfilesUpdateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedUpdateWithoutFilePathInput>
  create: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedCreateWithoutFilePathInput>
}

export type FilesOnProfilesUpdateWithWhereUniqueWithoutFilePathInput = {
  where: Prisma.FilesOnProfilesWhereUniqueInput
  data: Prisma.XOR<Prisma.FilesOnProfilesUpdateWithoutFilePathInput, Prisma.FilesOnProfilesUncheckedUpdateWithoutFilePathInput>
}

export type FilesOnProfilesUpdateManyWithWhereWithoutFilePathInput = {
  where: Prisma.FilesOnProfilesScalarWhereInput
  data: Prisma.XOR<Prisma.FilesOnProfilesUpdateManyMutationInput, Prisma.FilesOnProfilesUncheckedUpdateManyWithoutFilePathInput>
}

export type FilesOnProfilesScalarWhereInput = {
  AND?: Prisma.FilesOnProfilesScalarWhereInput | Prisma.FilesOnProfilesScalarWhereInput[]
  OR?: Prisma.FilesOnProfilesScalarWhereInput[]
  NOT?: Prisma.FilesOnProfilesScalarWhereInput | Prisma.FilesOnProfilesScalarWhereInput[]
  id?: Prisma.StringFilter<"FilesOnProfiles"> | string
  fileImagePath?: Prisma.StringFilter<"FilesOnProfiles"> | string
  profileId?: Prisma.StringFilter<"FilesOnProfiles"> | string
}

export type FilesOnProfilesCreateWithoutProfileInput = {
  id?: string
  filePath: Prisma.FilePathCreateNestedOneWithoutAvatarFilesInput
}

export type FilesOnProfilesUncheckedCreateWithoutProfileInput = {
  id?: string
  fileImagePath: string
}

export type FilesOnProfilesCreateOrConnectWithoutProfileInput = {
  where: Prisma.FilesOnProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedCreateWithoutProfileInput>
}

export type FilesOnProfilesUpsertWithoutProfileInput = {
  update: Prisma.XOR<Prisma.FilesOnProfilesUpdateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.FilesOnProfilesCreateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedCreateWithoutProfileInput>
  where?: Prisma.FilesOnProfilesWhereInput
}

export type FilesOnProfilesUpdateToOneWithWhereWithoutProfileInput = {
  where?: Prisma.FilesOnProfilesWhereInput
  data: Prisma.XOR<Prisma.FilesOnProfilesUpdateWithoutProfileInput, Prisma.FilesOnProfilesUncheckedUpdateWithoutProfileInput>
}

export type FilesOnProfilesUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.FilePathUpdateOneRequiredWithoutAvatarFilesNestedInput
}

export type FilesOnProfilesUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilesOnProfilesCreateManyFilePathInput = {
  id?: string
  profileId: string
}

export type FilesOnProfilesUpdateWithoutFilePathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profile?: Prisma.ProfilesUpdateOneRequiredWithoutAvatarPathNestedInput
}

export type FilesOnProfilesUncheckedUpdateWithoutFilePathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilesOnProfilesUncheckedUpdateManyWithoutFilePathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FilesOnProfilesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileImagePath?: boolean
  profileId?: boolean
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filesOnProfiles"]>

export type FilesOnProfilesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileImagePath?: boolean
  profileId?: boolean
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filesOnProfiles"]>

export type FilesOnProfilesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileImagePath?: boolean
  profileId?: boolean
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filesOnProfiles"]>

export type FilesOnProfilesSelectScalar = {
  id?: boolean
  fileImagePath?: boolean
  profileId?: boolean
}

export type FilesOnProfilesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileImagePath" | "profileId", ExtArgs["result"]["filesOnProfiles"]>
export type FilesOnProfilesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfilesDefaultArgs<ExtArgs>
}
export type FilesOnProfilesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfilesDefaultArgs<ExtArgs>
}
export type FilesOnProfilesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  profile?: boolean | Prisma.ProfilesDefaultArgs<ExtArgs>
}

export type $FilesOnProfilesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FilesOnProfiles"
  objects: {
    filePath: Prisma.$FilePathPayload<ExtArgs>
    profile: Prisma.$ProfilesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileImagePath: string
    profileId: string
  }, ExtArgs["result"]["filesOnProfiles"]>
  composites: {}
}

export type FilesOnProfilesGetPayload<S extends boolean | null | undefined | FilesOnProfilesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload, S>

export type FilesOnProfilesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FilesOnProfilesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FilesOnProfilesCountAggregateInputType | true
  }

export interface FilesOnProfilesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FilesOnProfiles'], meta: { name: 'FilesOnProfiles' } }
  /**
   * Find zero or one FilesOnProfiles that matches the filter.
   * @param {FilesOnProfilesFindUniqueArgs} args - Arguments to find a FilesOnProfiles
   * @example
   * // Get one FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FilesOnProfilesFindUniqueArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FilesOnProfiles that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FilesOnProfilesFindUniqueOrThrowArgs} args - Arguments to find a FilesOnProfiles
   * @example
   * // Get one FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FilesOnProfilesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FilesOnProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesFindFirstArgs} args - Arguments to find a FilesOnProfiles
   * @example
   * // Get one FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FilesOnProfilesFindFirstArgs>(args?: Prisma.SelectSubset<T, FilesOnProfilesFindFirstArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FilesOnProfiles that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesFindFirstOrThrowArgs} args - Arguments to find a FilesOnProfiles
   * @example
   * // Get one FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FilesOnProfilesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FilesOnProfilesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FilesOnProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.findMany()
   * 
   * // Get first 10 FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const filesOnProfilesWithIdOnly = await prisma.filesOnProfiles.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FilesOnProfilesFindManyArgs>(args?: Prisma.SelectSubset<T, FilesOnProfilesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FilesOnProfiles.
   * @param {FilesOnProfilesCreateArgs} args - Arguments to create a FilesOnProfiles.
   * @example
   * // Create one FilesOnProfiles
   * const FilesOnProfiles = await prisma.filesOnProfiles.create({
   *   data: {
   *     // ... data to create a FilesOnProfiles
   *   }
   * })
   * 
   */
  create<T extends FilesOnProfilesCreateArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesCreateArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FilesOnProfiles.
   * @param {FilesOnProfilesCreateManyArgs} args - Arguments to create many FilesOnProfiles.
   * @example
   * // Create many FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FilesOnProfilesCreateManyArgs>(args?: Prisma.SelectSubset<T, FilesOnProfilesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FilesOnProfiles and returns the data saved in the database.
   * @param {FilesOnProfilesCreateManyAndReturnArgs} args - Arguments to create many FilesOnProfiles.
   * @example
   * // Create many FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FilesOnProfiles and only return the `id`
   * const filesOnProfilesWithIdOnly = await prisma.filesOnProfiles.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FilesOnProfilesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FilesOnProfilesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FilesOnProfiles.
   * @param {FilesOnProfilesDeleteArgs} args - Arguments to delete one FilesOnProfiles.
   * @example
   * // Delete one FilesOnProfiles
   * const FilesOnProfiles = await prisma.filesOnProfiles.delete({
   *   where: {
   *     // ... filter to delete one FilesOnProfiles
   *   }
   * })
   * 
   */
  delete<T extends FilesOnProfilesDeleteArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesDeleteArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FilesOnProfiles.
   * @param {FilesOnProfilesUpdateArgs} args - Arguments to update one FilesOnProfiles.
   * @example
   * // Update one FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FilesOnProfilesUpdateArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesUpdateArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FilesOnProfiles.
   * @param {FilesOnProfilesDeleteManyArgs} args - Arguments to filter FilesOnProfiles to delete.
   * @example
   * // Delete a few FilesOnProfiles
   * const { count } = await prisma.filesOnProfiles.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FilesOnProfilesDeleteManyArgs>(args?: Prisma.SelectSubset<T, FilesOnProfilesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FilesOnProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FilesOnProfilesUpdateManyArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FilesOnProfiles and returns the data updated in the database.
   * @param {FilesOnProfilesUpdateManyAndReturnArgs} args - Arguments to update many FilesOnProfiles.
   * @example
   * // Update many FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FilesOnProfiles and only return the `id`
   * const filesOnProfilesWithIdOnly = await prisma.filesOnProfiles.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FilesOnProfilesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FilesOnProfiles.
   * @param {FilesOnProfilesUpsertArgs} args - Arguments to update or create a FilesOnProfiles.
   * @example
   * // Update or create a FilesOnProfiles
   * const filesOnProfiles = await prisma.filesOnProfiles.upsert({
   *   create: {
   *     // ... data to create a FilesOnProfiles
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FilesOnProfiles we want to update
   *   }
   * })
   */
  upsert<T extends FilesOnProfilesUpsertArgs>(args: Prisma.SelectSubset<T, FilesOnProfilesUpsertArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FilesOnProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesCountArgs} args - Arguments to filter FilesOnProfiles to count.
   * @example
   * // Count the number of FilesOnProfiles
   * const count = await prisma.filesOnProfiles.count({
   *   where: {
   *     // ... the filter for the FilesOnProfiles we want to count
   *   }
   * })
  **/
  count<T extends FilesOnProfilesCountArgs>(
    args?: Prisma.Subset<T, FilesOnProfilesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FilesOnProfilesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FilesOnProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FilesOnProfilesAggregateArgs>(args: Prisma.Subset<T, FilesOnProfilesAggregateArgs>): Prisma.PrismaPromise<GetFilesOnProfilesAggregateType<T>>

  /**
   * Group by FilesOnProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesOnProfilesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FilesOnProfilesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FilesOnProfilesGroupByArgs['orderBy'] }
      : { orderBy?: FilesOnProfilesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FilesOnProfilesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFilesOnProfilesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FilesOnProfiles model
 */
readonly fields: FilesOnProfilesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FilesOnProfiles.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FilesOnProfilesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  filePath<T extends Prisma.FilePathDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilePathDefaultArgs<ExtArgs>>): Prisma.Prisma__FilePathClient<runtime.Types.Result.GetResult<Prisma.$FilePathPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profile<T extends Prisma.ProfilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfilesDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FilesOnProfiles model
 */
export interface FilesOnProfilesFieldRefs {
  readonly id: Prisma.FieldRef<"FilesOnProfiles", 'String'>
  readonly fileImagePath: Prisma.FieldRef<"FilesOnProfiles", 'String'>
  readonly profileId: Prisma.FieldRef<"FilesOnProfiles", 'String'>
}
    

// Custom InputTypes
/**
 * FilesOnProfiles findUnique
 */
export type FilesOnProfilesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * Filter, which FilesOnProfiles to fetch.
   */
  where: Prisma.FilesOnProfilesWhereUniqueInput
}

/**
 * FilesOnProfiles findUniqueOrThrow
 */
export type FilesOnProfilesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * Filter, which FilesOnProfiles to fetch.
   */
  where: Prisma.FilesOnProfilesWhereUniqueInput
}

/**
 * FilesOnProfiles findFirst
 */
export type FilesOnProfilesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * Filter, which FilesOnProfiles to fetch.
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilesOnProfiles to fetch.
   */
  orderBy?: Prisma.FilesOnProfilesOrderByWithRelationInput | Prisma.FilesOnProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FilesOnProfiles.
   */
  cursor?: Prisma.FilesOnProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilesOnProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilesOnProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FilesOnProfiles.
   */
  distinct?: Prisma.FilesOnProfilesScalarFieldEnum | Prisma.FilesOnProfilesScalarFieldEnum[]
}

/**
 * FilesOnProfiles findFirstOrThrow
 */
export type FilesOnProfilesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * Filter, which FilesOnProfiles to fetch.
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilesOnProfiles to fetch.
   */
  orderBy?: Prisma.FilesOnProfilesOrderByWithRelationInput | Prisma.FilesOnProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FilesOnProfiles.
   */
  cursor?: Prisma.FilesOnProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilesOnProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilesOnProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FilesOnProfiles.
   */
  distinct?: Prisma.FilesOnProfilesScalarFieldEnum | Prisma.FilesOnProfilesScalarFieldEnum[]
}

/**
 * FilesOnProfiles findMany
 */
export type FilesOnProfilesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * Filter, which FilesOnProfiles to fetch.
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilesOnProfiles to fetch.
   */
  orderBy?: Prisma.FilesOnProfilesOrderByWithRelationInput | Prisma.FilesOnProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FilesOnProfiles.
   */
  cursor?: Prisma.FilesOnProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilesOnProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilesOnProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FilesOnProfiles.
   */
  distinct?: Prisma.FilesOnProfilesScalarFieldEnum | Prisma.FilesOnProfilesScalarFieldEnum[]
}

/**
 * FilesOnProfiles create
 */
export type FilesOnProfilesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * The data needed to create a FilesOnProfiles.
   */
  data: Prisma.XOR<Prisma.FilesOnProfilesCreateInput, Prisma.FilesOnProfilesUncheckedCreateInput>
}

/**
 * FilesOnProfiles createMany
 */
export type FilesOnProfilesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FilesOnProfiles.
   */
  data: Prisma.FilesOnProfilesCreateManyInput | Prisma.FilesOnProfilesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FilesOnProfiles createManyAndReturn
 */
export type FilesOnProfilesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * The data used to create many FilesOnProfiles.
   */
  data: Prisma.FilesOnProfilesCreateManyInput | Prisma.FilesOnProfilesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FilesOnProfiles update
 */
export type FilesOnProfilesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * The data needed to update a FilesOnProfiles.
   */
  data: Prisma.XOR<Prisma.FilesOnProfilesUpdateInput, Prisma.FilesOnProfilesUncheckedUpdateInput>
  /**
   * Choose, which FilesOnProfiles to update.
   */
  where: Prisma.FilesOnProfilesWhereUniqueInput
}

/**
 * FilesOnProfiles updateMany
 */
export type FilesOnProfilesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FilesOnProfiles.
   */
  data: Prisma.XOR<Prisma.FilesOnProfilesUpdateManyMutationInput, Prisma.FilesOnProfilesUncheckedUpdateManyInput>
  /**
   * Filter which FilesOnProfiles to update
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * Limit how many FilesOnProfiles to update.
   */
  limit?: number
}

/**
 * FilesOnProfiles updateManyAndReturn
 */
export type FilesOnProfilesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * The data used to update FilesOnProfiles.
   */
  data: Prisma.XOR<Prisma.FilesOnProfilesUpdateManyMutationInput, Prisma.FilesOnProfilesUncheckedUpdateManyInput>
  /**
   * Filter which FilesOnProfiles to update
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * Limit how many FilesOnProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FilesOnProfiles upsert
 */
export type FilesOnProfilesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * The filter to search for the FilesOnProfiles to update in case it exists.
   */
  where: Prisma.FilesOnProfilesWhereUniqueInput
  /**
   * In case the FilesOnProfiles found by the `where` argument doesn't exist, create a new FilesOnProfiles with this data.
   */
  create: Prisma.XOR<Prisma.FilesOnProfilesCreateInput, Prisma.FilesOnProfilesUncheckedCreateInput>
  /**
   * In case the FilesOnProfiles was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FilesOnProfilesUpdateInput, Prisma.FilesOnProfilesUncheckedUpdateInput>
}

/**
 * FilesOnProfiles delete
 */
export type FilesOnProfilesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  /**
   * Filter which FilesOnProfiles to delete.
   */
  where: Prisma.FilesOnProfilesWhereUniqueInput
}

/**
 * FilesOnProfiles deleteMany
 */
export type FilesOnProfilesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FilesOnProfiles to delete
   */
  where?: Prisma.FilesOnProfilesWhereInput
  /**
   * Limit how many FilesOnProfiles to delete.
   */
  limit?: number
}

/**
 * FilesOnProfiles without action
 */
export type FilesOnProfilesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
}
