
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FileOnPosts` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FileOnPosts
 * 
 */
export type FileOnPostsModel = runtime.Types.Result.DefaultSelection<Prisma.$FileOnPostsPayload>

export type AggregateFileOnPosts = {
  _count: FileOnPostsCountAggregateOutputType | null
  _min: FileOnPostsMinAggregateOutputType | null
  _max: FileOnPostsMaxAggregateOutputType | null
}

export type FileOnPostsMinAggregateOutputType = {
  id: string | null
  fileImagePath: string | null
  postId: string | null
}

export type FileOnPostsMaxAggregateOutputType = {
  id: string | null
  fileImagePath: string | null
  postId: string | null
}

export type FileOnPostsCountAggregateOutputType = {
  id: number
  fileImagePath: number
  postId: number
  _all: number
}


export type FileOnPostsMinAggregateInputType = {
  id?: true
  fileImagePath?: true
  postId?: true
}

export type FileOnPostsMaxAggregateInputType = {
  id?: true
  fileImagePath?: true
  postId?: true
}

export type FileOnPostsCountAggregateInputType = {
  id?: true
  fileImagePath?: true
  postId?: true
  _all?: true
}

export type FileOnPostsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileOnPosts to aggregate.
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileOnPosts to fetch.
   */
  orderBy?: Prisma.FileOnPostsOrderByWithRelationInput | Prisma.FileOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FileOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FileOnPosts
  **/
  _count?: true | FileOnPostsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FileOnPostsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FileOnPostsMaxAggregateInputType
}

export type GetFileOnPostsAggregateType<T extends FileOnPostsAggregateArgs> = {
      [P in keyof T & keyof AggregateFileOnPosts]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFileOnPosts[P]>
    : Prisma.GetScalarType<T[P], AggregateFileOnPosts[P]>
}




export type FileOnPostsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileOnPostsWhereInput
  orderBy?: Prisma.FileOnPostsOrderByWithAggregationInput | Prisma.FileOnPostsOrderByWithAggregationInput[]
  by: Prisma.FileOnPostsScalarFieldEnum[] | Prisma.FileOnPostsScalarFieldEnum
  having?: Prisma.FileOnPostsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FileOnPostsCountAggregateInputType | true
  _min?: FileOnPostsMinAggregateInputType
  _max?: FileOnPostsMaxAggregateInputType
}

export type FileOnPostsGroupByOutputType = {
  id: string
  fileImagePath: string
  postId: string
  _count: FileOnPostsCountAggregateOutputType | null
  _min: FileOnPostsMinAggregateOutputType | null
  _max: FileOnPostsMaxAggregateOutputType | null
}

export type GetFileOnPostsGroupByPayload<T extends FileOnPostsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileOnPostsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FileOnPostsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FileOnPostsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FileOnPostsGroupByOutputType[P]>
      }
    >
  >



export type FileOnPostsWhereInput = {
  AND?: Prisma.FileOnPostsWhereInput | Prisma.FileOnPostsWhereInput[]
  OR?: Prisma.FileOnPostsWhereInput[]
  NOT?: Prisma.FileOnPostsWhereInput | Prisma.FileOnPostsWhereInput[]
  id?: Prisma.StringFilter<"FileOnPosts"> | string
  fileImagePath?: Prisma.StringFilter<"FileOnPosts"> | string
  postId?: Prisma.StringFilter<"FileOnPosts"> | string
  filePath?: Prisma.XOR<Prisma.FilePathScalarRelationFilter, Prisma.FilePathWhereInput>
  post?: Prisma.XOR<Prisma.PostsScalarRelationFilter, Prisma.PostsWhereInput>
}

export type FileOnPostsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  filePath?: Prisma.FilePathOrderByWithRelationInput
  post?: Prisma.PostsOrderByWithRelationInput
}

export type FileOnPostsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FileOnPostsWhereInput | Prisma.FileOnPostsWhereInput[]
  OR?: Prisma.FileOnPostsWhereInput[]
  NOT?: Prisma.FileOnPostsWhereInput | Prisma.FileOnPostsWhereInput[]
  fileImagePath?: Prisma.StringFilter<"FileOnPosts"> | string
  postId?: Prisma.StringFilter<"FileOnPosts"> | string
  filePath?: Prisma.XOR<Prisma.FilePathScalarRelationFilter, Prisma.FilePathWhereInput>
  post?: Prisma.XOR<Prisma.PostsScalarRelationFilter, Prisma.PostsWhereInput>
}, "id">

export type FileOnPostsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  _count?: Prisma.FileOnPostsCountOrderByAggregateInput
  _max?: Prisma.FileOnPostsMaxOrderByAggregateInput
  _min?: Prisma.FileOnPostsMinOrderByAggregateInput
}

export type FileOnPostsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileOnPostsScalarWhereWithAggregatesInput | Prisma.FileOnPostsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FileOnPostsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FileOnPostsScalarWhereWithAggregatesInput | Prisma.FileOnPostsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FileOnPosts"> | string
  fileImagePath?: Prisma.StringWithAggregatesFilter<"FileOnPosts"> | string
  postId?: Prisma.StringWithAggregatesFilter<"FileOnPosts"> | string
}

export type FileOnPostsCreateInput = {
  id?: string
  filePath: Prisma.FilePathCreateNestedOneWithoutPostFilesInput
  post: Prisma.PostsCreateNestedOneWithoutPostFilesInput
}

export type FileOnPostsUncheckedCreateInput = {
  id?: string
  fileImagePath: string
  postId: string
}

export type FileOnPostsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.FilePathUpdateOneRequiredWithoutPostFilesNestedInput
  post?: Prisma.PostsUpdateOneRequiredWithoutPostFilesNestedInput
}

export type FileOnPostsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileOnPostsCreateManyInput = {
  id?: string
  fileImagePath: string
  postId: string
}

export type FileOnPostsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileOnPostsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileOnPostsListRelationFilter = {
  every?: Prisma.FileOnPostsWhereInput
  some?: Prisma.FileOnPostsWhereInput
  none?: Prisma.FileOnPostsWhereInput
}

export type FileOnPostsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FileOnPostsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type FileOnPostsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type FileOnPostsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileImagePath?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type FileOnPostsCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutPostInput, Prisma.FileOnPostsUncheckedCreateWithoutPostInput> | Prisma.FileOnPostsCreateWithoutPostInput[] | Prisma.FileOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutPostInput | Prisma.FileOnPostsCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.FileOnPostsCreateManyPostInputEnvelope
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
}

export type FileOnPostsUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutPostInput, Prisma.FileOnPostsUncheckedCreateWithoutPostInput> | Prisma.FileOnPostsCreateWithoutPostInput[] | Prisma.FileOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutPostInput | Prisma.FileOnPostsCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.FileOnPostsCreateManyPostInputEnvelope
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
}

export type FileOnPostsUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutPostInput, Prisma.FileOnPostsUncheckedCreateWithoutPostInput> | Prisma.FileOnPostsCreateWithoutPostInput[] | Prisma.FileOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutPostInput | Prisma.FileOnPostsCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.FileOnPostsUpsertWithWhereUniqueWithoutPostInput | Prisma.FileOnPostsUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.FileOnPostsCreateManyPostInputEnvelope
  set?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  disconnect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  delete?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  update?: Prisma.FileOnPostsUpdateWithWhereUniqueWithoutPostInput | Prisma.FileOnPostsUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.FileOnPostsUpdateManyWithWhereWithoutPostInput | Prisma.FileOnPostsUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.FileOnPostsScalarWhereInput | Prisma.FileOnPostsScalarWhereInput[]
}

export type FileOnPostsUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutPostInput, Prisma.FileOnPostsUncheckedCreateWithoutPostInput> | Prisma.FileOnPostsCreateWithoutPostInput[] | Prisma.FileOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutPostInput | Prisma.FileOnPostsCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.FileOnPostsUpsertWithWhereUniqueWithoutPostInput | Prisma.FileOnPostsUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.FileOnPostsCreateManyPostInputEnvelope
  set?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  disconnect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  delete?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  update?: Prisma.FileOnPostsUpdateWithWhereUniqueWithoutPostInput | Prisma.FileOnPostsUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.FileOnPostsUpdateManyWithWhereWithoutPostInput | Prisma.FileOnPostsUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.FileOnPostsScalarWhereInput | Prisma.FileOnPostsScalarWhereInput[]
}

export type FileOnPostsCreateNestedManyWithoutFilePathInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutFilePathInput, Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput> | Prisma.FileOnPostsCreateWithoutFilePathInput[] | Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput | Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput[]
  createMany?: Prisma.FileOnPostsCreateManyFilePathInputEnvelope
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
}

export type FileOnPostsUncheckedCreateNestedManyWithoutFilePathInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutFilePathInput, Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput> | Prisma.FileOnPostsCreateWithoutFilePathInput[] | Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput | Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput[]
  createMany?: Prisma.FileOnPostsCreateManyFilePathInputEnvelope
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
}

export type FileOnPostsUpdateManyWithoutFilePathNestedInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutFilePathInput, Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput> | Prisma.FileOnPostsCreateWithoutFilePathInput[] | Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput | Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput[]
  upsert?: Prisma.FileOnPostsUpsertWithWhereUniqueWithoutFilePathInput | Prisma.FileOnPostsUpsertWithWhereUniqueWithoutFilePathInput[]
  createMany?: Prisma.FileOnPostsCreateManyFilePathInputEnvelope
  set?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  disconnect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  delete?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  update?: Prisma.FileOnPostsUpdateWithWhereUniqueWithoutFilePathInput | Prisma.FileOnPostsUpdateWithWhereUniqueWithoutFilePathInput[]
  updateMany?: Prisma.FileOnPostsUpdateManyWithWhereWithoutFilePathInput | Prisma.FileOnPostsUpdateManyWithWhereWithoutFilePathInput[]
  deleteMany?: Prisma.FileOnPostsScalarWhereInput | Prisma.FileOnPostsScalarWhereInput[]
}

export type FileOnPostsUncheckedUpdateManyWithoutFilePathNestedInput = {
  create?: Prisma.XOR<Prisma.FileOnPostsCreateWithoutFilePathInput, Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput> | Prisma.FileOnPostsCreateWithoutFilePathInput[] | Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput[]
  connectOrCreate?: Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput | Prisma.FileOnPostsCreateOrConnectWithoutFilePathInput[]
  upsert?: Prisma.FileOnPostsUpsertWithWhereUniqueWithoutFilePathInput | Prisma.FileOnPostsUpsertWithWhereUniqueWithoutFilePathInput[]
  createMany?: Prisma.FileOnPostsCreateManyFilePathInputEnvelope
  set?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  disconnect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  delete?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  connect?: Prisma.FileOnPostsWhereUniqueInput | Prisma.FileOnPostsWhereUniqueInput[]
  update?: Prisma.FileOnPostsUpdateWithWhereUniqueWithoutFilePathInput | Prisma.FileOnPostsUpdateWithWhereUniqueWithoutFilePathInput[]
  updateMany?: Prisma.FileOnPostsUpdateManyWithWhereWithoutFilePathInput | Prisma.FileOnPostsUpdateManyWithWhereWithoutFilePathInput[]
  deleteMany?: Prisma.FileOnPostsScalarWhereInput | Prisma.FileOnPostsScalarWhereInput[]
}

export type FileOnPostsCreateWithoutPostInput = {
  id?: string
  filePath: Prisma.FilePathCreateNestedOneWithoutPostFilesInput
}

export type FileOnPostsUncheckedCreateWithoutPostInput = {
  id?: string
  fileImagePath: string
}

export type FileOnPostsCreateOrConnectWithoutPostInput = {
  where: Prisma.FileOnPostsWhereUniqueInput
  create: Prisma.XOR<Prisma.FileOnPostsCreateWithoutPostInput, Prisma.FileOnPostsUncheckedCreateWithoutPostInput>
}

export type FileOnPostsCreateManyPostInputEnvelope = {
  data: Prisma.FileOnPostsCreateManyPostInput | Prisma.FileOnPostsCreateManyPostInput[]
  skipDuplicates?: boolean
}

export type FileOnPostsUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.FileOnPostsWhereUniqueInput
  update: Prisma.XOR<Prisma.FileOnPostsUpdateWithoutPostInput, Prisma.FileOnPostsUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.FileOnPostsCreateWithoutPostInput, Prisma.FileOnPostsUncheckedCreateWithoutPostInput>
}

export type FileOnPostsUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.FileOnPostsWhereUniqueInput
  data: Prisma.XOR<Prisma.FileOnPostsUpdateWithoutPostInput, Prisma.FileOnPostsUncheckedUpdateWithoutPostInput>
}

export type FileOnPostsUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.FileOnPostsScalarWhereInput
  data: Prisma.XOR<Prisma.FileOnPostsUpdateManyMutationInput, Prisma.FileOnPostsUncheckedUpdateManyWithoutPostInput>
}

export type FileOnPostsScalarWhereInput = {
  AND?: Prisma.FileOnPostsScalarWhereInput | Prisma.FileOnPostsScalarWhereInput[]
  OR?: Prisma.FileOnPostsScalarWhereInput[]
  NOT?: Prisma.FileOnPostsScalarWhereInput | Prisma.FileOnPostsScalarWhereInput[]
  id?: Prisma.StringFilter<"FileOnPosts"> | string
  fileImagePath?: Prisma.StringFilter<"FileOnPosts"> | string
  postId?: Prisma.StringFilter<"FileOnPosts"> | string
}

export type FileOnPostsCreateWithoutFilePathInput = {
  id?: string
  post: Prisma.PostsCreateNestedOneWithoutPostFilesInput
}

export type FileOnPostsUncheckedCreateWithoutFilePathInput = {
  id?: string
  postId: string
}

export type FileOnPostsCreateOrConnectWithoutFilePathInput = {
  where: Prisma.FileOnPostsWhereUniqueInput
  create: Prisma.XOR<Prisma.FileOnPostsCreateWithoutFilePathInput, Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput>
}

export type FileOnPostsCreateManyFilePathInputEnvelope = {
  data: Prisma.FileOnPostsCreateManyFilePathInput | Prisma.FileOnPostsCreateManyFilePathInput[]
  skipDuplicates?: boolean
}

export type FileOnPostsUpsertWithWhereUniqueWithoutFilePathInput = {
  where: Prisma.FileOnPostsWhereUniqueInput
  update: Prisma.XOR<Prisma.FileOnPostsUpdateWithoutFilePathInput, Prisma.FileOnPostsUncheckedUpdateWithoutFilePathInput>
  create: Prisma.XOR<Prisma.FileOnPostsCreateWithoutFilePathInput, Prisma.FileOnPostsUncheckedCreateWithoutFilePathInput>
}

export type FileOnPostsUpdateWithWhereUniqueWithoutFilePathInput = {
  where: Prisma.FileOnPostsWhereUniqueInput
  data: Prisma.XOR<Prisma.FileOnPostsUpdateWithoutFilePathInput, Prisma.FileOnPostsUncheckedUpdateWithoutFilePathInput>
}

export type FileOnPostsUpdateManyWithWhereWithoutFilePathInput = {
  where: Prisma.FileOnPostsScalarWhereInput
  data: Prisma.XOR<Prisma.FileOnPostsUpdateManyMutationInput, Prisma.FileOnPostsUncheckedUpdateManyWithoutFilePathInput>
}

export type FileOnPostsCreateManyPostInput = {
  id?: string
  fileImagePath: string
}

export type FileOnPostsUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filePath?: Prisma.FilePathUpdateOneRequiredWithoutPostFilesNestedInput
}

export type FileOnPostsUncheckedUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileOnPostsUncheckedUpdateManyWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileImagePath?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileOnPostsCreateManyFilePathInput = {
  id?: string
  postId: string
}

export type FileOnPostsUpdateWithoutFilePathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  post?: Prisma.PostsUpdateOneRequiredWithoutPostFilesNestedInput
}

export type FileOnPostsUncheckedUpdateWithoutFilePathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FileOnPostsUncheckedUpdateManyWithoutFilePathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FileOnPostsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileImagePath?: boolean
  postId?: boolean
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileOnPosts"]>

export type FileOnPostsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileImagePath?: boolean
  postId?: boolean
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileOnPosts"]>

export type FileOnPostsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileImagePath?: boolean
  postId?: boolean
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileOnPosts"]>

export type FileOnPostsSelectScalar = {
  id?: boolean
  fileImagePath?: boolean
  postId?: boolean
}

export type FileOnPostsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileImagePath" | "postId", ExtArgs["result"]["fileOnPosts"]>
export type FileOnPostsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
}
export type FileOnPostsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
}
export type FileOnPostsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  filePath?: boolean | Prisma.FilePathDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
}

export type $FileOnPostsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FileOnPosts"
  objects: {
    filePath: Prisma.$FilePathPayload<ExtArgs>
    post: Prisma.$PostsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileImagePath: string
    postId: string
  }, ExtArgs["result"]["fileOnPosts"]>
  composites: {}
}

export type FileOnPostsGetPayload<S extends boolean | null | undefined | FileOnPostsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload, S>

export type FileOnPostsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FileOnPostsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FileOnPostsCountAggregateInputType | true
  }

export interface FileOnPostsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FileOnPosts'], meta: { name: 'FileOnPosts' } }
  /**
   * Find zero or one FileOnPosts that matches the filter.
   * @param {FileOnPostsFindUniqueArgs} args - Arguments to find a FileOnPosts
   * @example
   * // Get one FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileOnPostsFindUniqueArgs>(args: Prisma.SelectSubset<T, FileOnPostsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FileOnPosts that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileOnPostsFindUniqueOrThrowArgs} args - Arguments to find a FileOnPosts
   * @example
   * // Get one FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileOnPostsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FileOnPostsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileOnPosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsFindFirstArgs} args - Arguments to find a FileOnPosts
   * @example
   * // Get one FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileOnPostsFindFirstArgs>(args?: Prisma.SelectSubset<T, FileOnPostsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileOnPosts that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsFindFirstOrThrowArgs} args - Arguments to find a FileOnPosts
   * @example
   * // Get one FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileOnPostsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FileOnPostsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FileOnPosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.findMany()
   * 
   * // Get first 10 FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fileOnPostsWithIdOnly = await prisma.fileOnPosts.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FileOnPostsFindManyArgs>(args?: Prisma.SelectSubset<T, FileOnPostsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FileOnPosts.
   * @param {FileOnPostsCreateArgs} args - Arguments to create a FileOnPosts.
   * @example
   * // Create one FileOnPosts
   * const FileOnPosts = await prisma.fileOnPosts.create({
   *   data: {
   *     // ... data to create a FileOnPosts
   *   }
   * })
   * 
   */
  create<T extends FileOnPostsCreateArgs>(args: Prisma.SelectSubset<T, FileOnPostsCreateArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FileOnPosts.
   * @param {FileOnPostsCreateManyArgs} args - Arguments to create many FileOnPosts.
   * @example
   * // Create many FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FileOnPostsCreateManyArgs>(args?: Prisma.SelectSubset<T, FileOnPostsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FileOnPosts and returns the data saved in the database.
   * @param {FileOnPostsCreateManyAndReturnArgs} args - Arguments to create many FileOnPosts.
   * @example
   * // Create many FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FileOnPosts and only return the `id`
   * const fileOnPostsWithIdOnly = await prisma.fileOnPosts.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FileOnPostsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FileOnPostsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FileOnPosts.
   * @param {FileOnPostsDeleteArgs} args - Arguments to delete one FileOnPosts.
   * @example
   * // Delete one FileOnPosts
   * const FileOnPosts = await prisma.fileOnPosts.delete({
   *   where: {
   *     // ... filter to delete one FileOnPosts
   *   }
   * })
   * 
   */
  delete<T extends FileOnPostsDeleteArgs>(args: Prisma.SelectSubset<T, FileOnPostsDeleteArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FileOnPosts.
   * @param {FileOnPostsUpdateArgs} args - Arguments to update one FileOnPosts.
   * @example
   * // Update one FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FileOnPostsUpdateArgs>(args: Prisma.SelectSubset<T, FileOnPostsUpdateArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FileOnPosts.
   * @param {FileOnPostsDeleteManyArgs} args - Arguments to filter FileOnPosts to delete.
   * @example
   * // Delete a few FileOnPosts
   * const { count } = await prisma.fileOnPosts.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FileOnPostsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FileOnPostsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FileOnPostsUpdateManyArgs>(args: Prisma.SelectSubset<T, FileOnPostsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileOnPosts and returns the data updated in the database.
   * @param {FileOnPostsUpdateManyAndReturnArgs} args - Arguments to update many FileOnPosts.
   * @example
   * // Update many FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FileOnPosts and only return the `id`
   * const fileOnPostsWithIdOnly = await prisma.fileOnPosts.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FileOnPostsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FileOnPostsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FileOnPosts.
   * @param {FileOnPostsUpsertArgs} args - Arguments to update or create a FileOnPosts.
   * @example
   * // Update or create a FileOnPosts
   * const fileOnPosts = await prisma.fileOnPosts.upsert({
   *   create: {
   *     // ... data to create a FileOnPosts
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FileOnPosts we want to update
   *   }
   * })
   */
  upsert<T extends FileOnPostsUpsertArgs>(args: Prisma.SelectSubset<T, FileOnPostsUpsertArgs<ExtArgs>>): Prisma.Prisma__FileOnPostsClient<runtime.Types.Result.GetResult<Prisma.$FileOnPostsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FileOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsCountArgs} args - Arguments to filter FileOnPosts to count.
   * @example
   * // Count the number of FileOnPosts
   * const count = await prisma.fileOnPosts.count({
   *   where: {
   *     // ... the filter for the FileOnPosts we want to count
   *   }
   * })
  **/
  count<T extends FileOnPostsCountArgs>(
    args?: Prisma.Subset<T, FileOnPostsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileOnPostsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FileOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FileOnPostsAggregateArgs>(args: Prisma.Subset<T, FileOnPostsAggregateArgs>): Prisma.PrismaPromise<GetFileOnPostsAggregateType<T>>

  /**
   * Group by FileOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileOnPostsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FileOnPostsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FileOnPostsGroupByArgs['orderBy'] }
      : { orderBy?: FileOnPostsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FileOnPostsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFileOnPostsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FileOnPosts model
 */
readonly fields: FileOnPostsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FileOnPosts.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileOnPostsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  filePath<T extends Prisma.FilePathDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilePathDefaultArgs<ExtArgs>>): Prisma.Prisma__FilePathClient<runtime.Types.Result.GetResult<Prisma.$FilePathPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  post<T extends Prisma.PostsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostsDefaultArgs<ExtArgs>>): Prisma.Prisma__PostsClient<runtime.Types.Result.GetResult<Prisma.$PostsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FileOnPosts model
 */
export interface FileOnPostsFieldRefs {
  readonly id: Prisma.FieldRef<"FileOnPosts", 'String'>
  readonly fileImagePath: Prisma.FieldRef<"FileOnPosts", 'String'>
  readonly postId: Prisma.FieldRef<"FileOnPosts", 'String'>
}
    

// Custom InputTypes
/**
 * FileOnPosts findUnique
 */
export type FileOnPostsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which FileOnPosts to fetch.
   */
  where: Prisma.FileOnPostsWhereUniqueInput
}

/**
 * FileOnPosts findUniqueOrThrow
 */
export type FileOnPostsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which FileOnPosts to fetch.
   */
  where: Prisma.FileOnPostsWhereUniqueInput
}

/**
 * FileOnPosts findFirst
 */
export type FileOnPostsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which FileOnPosts to fetch.
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileOnPosts to fetch.
   */
  orderBy?: Prisma.FileOnPostsOrderByWithRelationInput | Prisma.FileOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileOnPosts.
   */
  cursor?: Prisma.FileOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileOnPosts.
   */
  distinct?: Prisma.FileOnPostsScalarFieldEnum | Prisma.FileOnPostsScalarFieldEnum[]
}

/**
 * FileOnPosts findFirstOrThrow
 */
export type FileOnPostsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which FileOnPosts to fetch.
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileOnPosts to fetch.
   */
  orderBy?: Prisma.FileOnPostsOrderByWithRelationInput | Prisma.FileOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileOnPosts.
   */
  cursor?: Prisma.FileOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileOnPosts.
   */
  distinct?: Prisma.FileOnPostsScalarFieldEnum | Prisma.FileOnPostsScalarFieldEnum[]
}

/**
 * FileOnPosts findMany
 */
export type FileOnPostsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which FileOnPosts to fetch.
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileOnPosts to fetch.
   */
  orderBy?: Prisma.FileOnPostsOrderByWithRelationInput | Prisma.FileOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FileOnPosts.
   */
  cursor?: Prisma.FileOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileOnPosts.
   */
  distinct?: Prisma.FileOnPostsScalarFieldEnum | Prisma.FileOnPostsScalarFieldEnum[]
}

/**
 * FileOnPosts create
 */
export type FileOnPostsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * The data needed to create a FileOnPosts.
   */
  data: Prisma.XOR<Prisma.FileOnPostsCreateInput, Prisma.FileOnPostsUncheckedCreateInput>
}

/**
 * FileOnPosts createMany
 */
export type FileOnPostsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FileOnPosts.
   */
  data: Prisma.FileOnPostsCreateManyInput | Prisma.FileOnPostsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FileOnPosts createManyAndReturn
 */
export type FileOnPostsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * The data used to create many FileOnPosts.
   */
  data: Prisma.FileOnPostsCreateManyInput | Prisma.FileOnPostsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FileOnPosts update
 */
export type FileOnPostsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * The data needed to update a FileOnPosts.
   */
  data: Prisma.XOR<Prisma.FileOnPostsUpdateInput, Prisma.FileOnPostsUncheckedUpdateInput>
  /**
   * Choose, which FileOnPosts to update.
   */
  where: Prisma.FileOnPostsWhereUniqueInput
}

/**
 * FileOnPosts updateMany
 */
export type FileOnPostsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FileOnPosts.
   */
  data: Prisma.XOR<Prisma.FileOnPostsUpdateManyMutationInput, Prisma.FileOnPostsUncheckedUpdateManyInput>
  /**
   * Filter which FileOnPosts to update
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * Limit how many FileOnPosts to update.
   */
  limit?: number
}

/**
 * FileOnPosts updateManyAndReturn
 */
export type FileOnPostsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * The data used to update FileOnPosts.
   */
  data: Prisma.XOR<Prisma.FileOnPostsUpdateManyMutationInput, Prisma.FileOnPostsUncheckedUpdateManyInput>
  /**
   * Filter which FileOnPosts to update
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * Limit how many FileOnPosts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FileOnPosts upsert
 */
export type FileOnPostsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * The filter to search for the FileOnPosts to update in case it exists.
   */
  where: Prisma.FileOnPostsWhereUniqueInput
  /**
   * In case the FileOnPosts found by the `where` argument doesn't exist, create a new FileOnPosts with this data.
   */
  create: Prisma.XOR<Prisma.FileOnPostsCreateInput, Prisma.FileOnPostsUncheckedCreateInput>
  /**
   * In case the FileOnPosts was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileOnPostsUpdateInput, Prisma.FileOnPostsUncheckedUpdateInput>
}

/**
 * FileOnPosts delete
 */
export type FileOnPostsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
  /**
   * Filter which FileOnPosts to delete.
   */
  where: Prisma.FileOnPostsWhereUniqueInput
}

/**
 * FileOnPosts deleteMany
 */
export type FileOnPostsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileOnPosts to delete
   */
  where?: Prisma.FileOnPostsWhereInput
  /**
   * Limit how many FileOnPosts to delete.
   */
  limit?: number
}

/**
 * FileOnPosts without action
 */
export type FileOnPostsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileOnPosts
   */
  select?: Prisma.FileOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileOnPosts
   */
  omit?: Prisma.FileOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileOnPostsInclude<ExtArgs> | null
}
