
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Profiles` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Profiles
 * 
 */
export type ProfilesModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfilesPayload>

export type AggregateProfiles = {
  _count: ProfilesCountAggregateOutputType | null
  _min: ProfilesMinAggregateOutputType | null
  _max: ProfilesMaxAggregateOutputType | null
}

export type ProfilesMinAggregateOutputType = {
  id: string | null
  username: string | null
  userId: string | null
  phoneNumber: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfilesMaxAggregateOutputType = {
  id: string | null
  username: string | null
  userId: string | null
  phoneNumber: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProfilesCountAggregateOutputType = {
  id: number
  username: number
  userId: number
  phoneNumber: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProfilesMinAggregateInputType = {
  id?: true
  username?: true
  userId?: true
  phoneNumber?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfilesMaxAggregateInputType = {
  id?: true
  username?: true
  userId?: true
  phoneNumber?: true
  createdAt?: true
  updatedAt?: true
}

export type ProfilesCountAggregateInputType = {
  id?: true
  username?: true
  userId?: true
  phoneNumber?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProfilesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profiles to aggregate.
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfilesOrderByWithRelationInput | Prisma.ProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Profiles
  **/
  _count?: true | ProfilesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfilesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfilesMaxAggregateInputType
}

export type GetProfilesAggregateType<T extends ProfilesAggregateArgs> = {
      [P in keyof T & keyof AggregateProfiles]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfiles[P]>
    : Prisma.GetScalarType<T[P], AggregateProfiles[P]>
}




export type ProfilesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfilesWhereInput
  orderBy?: Prisma.ProfilesOrderByWithAggregationInput | Prisma.ProfilesOrderByWithAggregationInput[]
  by: Prisma.ProfilesScalarFieldEnum[] | Prisma.ProfilesScalarFieldEnum
  having?: Prisma.ProfilesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfilesCountAggregateInputType | true
  _min?: ProfilesMinAggregateInputType
  _max?: ProfilesMaxAggregateInputType
}

export type ProfilesGroupByOutputType = {
  id: string
  username: string
  userId: string
  phoneNumber: string
  createdAt: Date
  updatedAt: Date
  _count: ProfilesCountAggregateOutputType | null
  _min: ProfilesMinAggregateOutputType | null
  _max: ProfilesMaxAggregateOutputType | null
}

export type GetProfilesGroupByPayload<T extends ProfilesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfilesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfilesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfilesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfilesGroupByOutputType[P]>
      }
    >
  >



export type ProfilesWhereInput = {
  AND?: Prisma.ProfilesWhereInput | Prisma.ProfilesWhereInput[]
  OR?: Prisma.ProfilesWhereInput[]
  NOT?: Prisma.ProfilesWhereInput | Prisma.ProfilesWhereInput[]
  id?: Prisma.StringFilter<"Profiles"> | string
  username?: Prisma.StringFilter<"Profiles"> | string
  userId?: Prisma.StringFilter<"Profiles"> | string
  phoneNumber?: Prisma.StringFilter<"Profiles"> | string
  createdAt?: Prisma.DateTimeFilter<"Profiles"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profiles"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  avatarPath?: Prisma.XOR<Prisma.FilesOnProfilesNullableScalarRelationFilter, Prisma.FilesOnProfilesWhereInput> | null
}

export type ProfilesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  avatarPath?: Prisma.FilesOnProfilesOrderByWithRelationInput
}

export type ProfilesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  username?: string
  userId?: string
  AND?: Prisma.ProfilesWhereInput | Prisma.ProfilesWhereInput[]
  OR?: Prisma.ProfilesWhereInput[]
  NOT?: Prisma.ProfilesWhereInput | Prisma.ProfilesWhereInput[]
  phoneNumber?: Prisma.StringFilter<"Profiles"> | string
  createdAt?: Prisma.DateTimeFilter<"Profiles"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Profiles"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  avatarPath?: Prisma.XOR<Prisma.FilesOnProfilesNullableScalarRelationFilter, Prisma.FilesOnProfilesWhereInput> | null
}, "id" | "username" | "userId">

export type ProfilesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProfilesCountOrderByAggregateInput
  _max?: Prisma.ProfilesMaxOrderByAggregateInput
  _min?: Prisma.ProfilesMinOrderByAggregateInput
}

export type ProfilesScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfilesScalarWhereWithAggregatesInput | Prisma.ProfilesScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfilesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfilesScalarWhereWithAggregatesInput | Prisma.ProfilesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Profiles"> | string
  username?: Prisma.StringWithAggregatesFilter<"Profiles"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Profiles"> | string
  phoneNumber?: Prisma.StringWithAggregatesFilter<"Profiles"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Profiles"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Profiles"> | Date | string
}

export type ProfilesCreateInput = {
  id?: string
  username: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutProfileUserInput
  avatarPath?: Prisma.FilesOnProfilesCreateNestedOneWithoutProfileInput
}

export type ProfilesUncheckedCreateInput = {
  id?: string
  username: string
  userId: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarPath?: Prisma.FilesOnProfilesUncheckedCreateNestedOneWithoutProfileInput
}

export type ProfilesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutProfileUserNestedInput
  avatarPath?: Prisma.FilesOnProfilesUpdateOneWithoutProfileNestedInput
}

export type ProfilesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarPath?: Prisma.FilesOnProfilesUncheckedUpdateOneWithoutProfileNestedInput
}

export type ProfilesCreateManyInput = {
  id?: string
  username: string
  userId: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProfilesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfilesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfilesNullableScalarRelationFilter = {
  is?: Prisma.ProfilesWhereInput | null
  isNot?: Prisma.ProfilesWhereInput | null
}

export type ProfilesScalarRelationFilter = {
  is?: Prisma.ProfilesWhereInput
  isNot?: Prisma.ProfilesWhereInput
}

export type ProfilesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfilesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfilesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProfilesCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProfilesCreateWithoutUserInput, Prisma.ProfilesUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfilesCreateOrConnectWithoutUserInput
  connect?: Prisma.ProfilesWhereUniqueInput
}

export type ProfilesUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProfilesCreateWithoutUserInput, Prisma.ProfilesUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfilesCreateOrConnectWithoutUserInput
  connect?: Prisma.ProfilesWhereUniqueInput
}

export type ProfilesUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProfilesCreateWithoutUserInput, Prisma.ProfilesUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfilesCreateOrConnectWithoutUserInput
  upsert?: Prisma.ProfilesUpsertWithoutUserInput
  disconnect?: Prisma.ProfilesWhereInput | boolean
  delete?: Prisma.ProfilesWhereInput | boolean
  connect?: Prisma.ProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfilesUpdateToOneWithWhereWithoutUserInput, Prisma.ProfilesUpdateWithoutUserInput>, Prisma.ProfilesUncheckedUpdateWithoutUserInput>
}

export type ProfilesUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProfilesCreateWithoutUserInput, Prisma.ProfilesUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.ProfilesCreateOrConnectWithoutUserInput
  upsert?: Prisma.ProfilesUpsertWithoutUserInput
  disconnect?: Prisma.ProfilesWhereInput | boolean
  delete?: Prisma.ProfilesWhereInput | boolean
  connect?: Prisma.ProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfilesUpdateToOneWithWhereWithoutUserInput, Prisma.ProfilesUpdateWithoutUserInput>, Prisma.ProfilesUncheckedUpdateWithoutUserInput>
}

export type ProfilesCreateNestedOneWithoutAvatarPathInput = {
  create?: Prisma.XOR<Prisma.ProfilesCreateWithoutAvatarPathInput, Prisma.ProfilesUncheckedCreateWithoutAvatarPathInput>
  connectOrCreate?: Prisma.ProfilesCreateOrConnectWithoutAvatarPathInput
  connect?: Prisma.ProfilesWhereUniqueInput
}

export type ProfilesUpdateOneRequiredWithoutAvatarPathNestedInput = {
  create?: Prisma.XOR<Prisma.ProfilesCreateWithoutAvatarPathInput, Prisma.ProfilesUncheckedCreateWithoutAvatarPathInput>
  connectOrCreate?: Prisma.ProfilesCreateOrConnectWithoutAvatarPathInput
  upsert?: Prisma.ProfilesUpsertWithoutAvatarPathInput
  connect?: Prisma.ProfilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProfilesUpdateToOneWithWhereWithoutAvatarPathInput, Prisma.ProfilesUpdateWithoutAvatarPathInput>, Prisma.ProfilesUncheckedUpdateWithoutAvatarPathInput>
}

export type ProfilesCreateWithoutUserInput = {
  id?: string
  username: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarPath?: Prisma.FilesOnProfilesCreateNestedOneWithoutProfileInput
}

export type ProfilesUncheckedCreateWithoutUserInput = {
  id?: string
  username: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
  avatarPath?: Prisma.FilesOnProfilesUncheckedCreateNestedOneWithoutProfileInput
}

export type ProfilesCreateOrConnectWithoutUserInput = {
  where: Prisma.ProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfilesCreateWithoutUserInput, Prisma.ProfilesUncheckedCreateWithoutUserInput>
}

export type ProfilesUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.ProfilesUpdateWithoutUserInput, Prisma.ProfilesUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ProfilesCreateWithoutUserInput, Prisma.ProfilesUncheckedCreateWithoutUserInput>
  where?: Prisma.ProfilesWhereInput
}

export type ProfilesUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.ProfilesWhereInput
  data: Prisma.XOR<Prisma.ProfilesUpdateWithoutUserInput, Prisma.ProfilesUncheckedUpdateWithoutUserInput>
}

export type ProfilesUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarPath?: Prisma.FilesOnProfilesUpdateOneWithoutProfileNestedInput
}

export type ProfilesUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  avatarPath?: Prisma.FilesOnProfilesUncheckedUpdateOneWithoutProfileNestedInput
}

export type ProfilesCreateWithoutAvatarPathInput = {
  id?: string
  username: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutProfileUserInput
}

export type ProfilesUncheckedCreateWithoutAvatarPathInput = {
  id?: string
  username: string
  userId: string
  phoneNumber: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProfilesCreateOrConnectWithoutAvatarPathInput = {
  where: Prisma.ProfilesWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfilesCreateWithoutAvatarPathInput, Prisma.ProfilesUncheckedCreateWithoutAvatarPathInput>
}

export type ProfilesUpsertWithoutAvatarPathInput = {
  update: Prisma.XOR<Prisma.ProfilesUpdateWithoutAvatarPathInput, Prisma.ProfilesUncheckedUpdateWithoutAvatarPathInput>
  create: Prisma.XOR<Prisma.ProfilesCreateWithoutAvatarPathInput, Prisma.ProfilesUncheckedCreateWithoutAvatarPathInput>
  where?: Prisma.ProfilesWhereInput
}

export type ProfilesUpdateToOneWithWhereWithoutAvatarPathInput = {
  where?: Prisma.ProfilesWhereInput
  data: Prisma.XOR<Prisma.ProfilesUpdateWithoutAvatarPathInput, Prisma.ProfilesUncheckedUpdateWithoutAvatarPathInput>
}

export type ProfilesUpdateWithoutAvatarPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutProfileUserNestedInput
}

export type ProfilesUncheckedUpdateWithoutAvatarPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProfilesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  userId?: boolean
  phoneNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  avatarPath?: boolean | Prisma.Profiles$avatarPathArgs<ExtArgs>
}, ExtArgs["result"]["profiles"]>

export type ProfilesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  userId?: boolean
  phoneNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profiles"]>

export type ProfilesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  userId?: boolean
  phoneNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profiles"]>

export type ProfilesSelectScalar = {
  id?: boolean
  username?: boolean
  userId?: boolean
  phoneNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProfilesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "userId" | "phoneNumber" | "createdAt" | "updatedAt", ExtArgs["result"]["profiles"]>
export type ProfilesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  avatarPath?: boolean | Prisma.Profiles$avatarPathArgs<ExtArgs>
}
export type ProfilesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ProfilesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ProfilesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Profiles"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    avatarPath: Prisma.$FilesOnProfilesPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    username: string
    userId: string
    phoneNumber: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["profiles"]>
  composites: {}
}

export type ProfilesGetPayload<S extends boolean | null | undefined | ProfilesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfilesPayload, S>

export type ProfilesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfilesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfilesCountAggregateInputType | true
  }

export interface ProfilesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Profiles'], meta: { name: 'Profiles' } }
  /**
   * Find zero or one Profiles that matches the filter.
   * @param {ProfilesFindUniqueArgs} args - Arguments to find a Profiles
   * @example
   * // Get one Profiles
   * const profiles = await prisma.profiles.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfilesFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfilesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Profiles that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfilesFindUniqueOrThrowArgs} args - Arguments to find a Profiles
   * @example
   * // Get one Profiles
   * const profiles = await prisma.profiles.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfilesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfilesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesFindFirstArgs} args - Arguments to find a Profiles
   * @example
   * // Get one Profiles
   * const profiles = await prisma.profiles.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfilesFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfilesFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Profiles that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesFindFirstOrThrowArgs} args - Arguments to find a Profiles
   * @example
   * // Get one Profiles
   * const profiles = await prisma.profiles.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfilesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfilesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Profiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Profiles
   * const profiles = await prisma.profiles.findMany()
   * 
   * // Get first 10 Profiles
   * const profiles = await prisma.profiles.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profilesWithIdOnly = await prisma.profiles.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfilesFindManyArgs>(args?: Prisma.SelectSubset<T, ProfilesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Profiles.
   * @param {ProfilesCreateArgs} args - Arguments to create a Profiles.
   * @example
   * // Create one Profiles
   * const Profiles = await prisma.profiles.create({
   *   data: {
   *     // ... data to create a Profiles
   *   }
   * })
   * 
   */
  create<T extends ProfilesCreateArgs>(args: Prisma.SelectSubset<T, ProfilesCreateArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Profiles.
   * @param {ProfilesCreateManyArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profiles = await prisma.profiles.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfilesCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfilesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Profiles and returns the data saved in the database.
   * @param {ProfilesCreateManyAndReturnArgs} args - Arguments to create many Profiles.
   * @example
   * // Create many Profiles
   * const profiles = await prisma.profiles.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Profiles and only return the `id`
   * const profilesWithIdOnly = await prisma.profiles.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProfilesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProfilesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Profiles.
   * @param {ProfilesDeleteArgs} args - Arguments to delete one Profiles.
   * @example
   * // Delete one Profiles
   * const Profiles = await prisma.profiles.delete({
   *   where: {
   *     // ... filter to delete one Profiles
   *   }
   * })
   * 
   */
  delete<T extends ProfilesDeleteArgs>(args: Prisma.SelectSubset<T, ProfilesDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Profiles.
   * @param {ProfilesUpdateArgs} args - Arguments to update one Profiles.
   * @example
   * // Update one Profiles
   * const profiles = await prisma.profiles.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfilesUpdateArgs>(args: Prisma.SelectSubset<T, ProfilesUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Profiles.
   * @param {ProfilesDeleteManyArgs} args - Arguments to filter Profiles to delete.
   * @example
   * // Delete a few Profiles
   * const { count } = await prisma.profiles.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfilesDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfilesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Profiles
   * const profiles = await prisma.profiles.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfilesUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfilesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Profiles and returns the data updated in the database.
   * @param {ProfilesUpdateManyAndReturnArgs} args - Arguments to update many Profiles.
   * @example
   * // Update many Profiles
   * const profiles = await prisma.profiles.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Profiles and only return the `id`
   * const profilesWithIdOnly = await prisma.profiles.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProfilesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProfilesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Profiles.
   * @param {ProfilesUpsertArgs} args - Arguments to update or create a Profiles.
   * @example
   * // Update or create a Profiles
   * const profiles = await prisma.profiles.upsert({
   *   create: {
   *     // ... data to create a Profiles
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Profiles we want to update
   *   }
   * })
   */
  upsert<T extends ProfilesUpsertArgs>(args: Prisma.SelectSubset<T, ProfilesUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfilesClient<runtime.Types.Result.GetResult<Prisma.$ProfilesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesCountArgs} args - Arguments to filter Profiles to count.
   * @example
   * // Count the number of Profiles
   * const count = await prisma.profiles.count({
   *   where: {
   *     // ... the filter for the Profiles we want to count
   *   }
   * })
  **/
  count<T extends ProfilesCountArgs>(
    args?: Prisma.Subset<T, ProfilesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfilesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfilesAggregateArgs>(args: Prisma.Subset<T, ProfilesAggregateArgs>): Prisma.PrismaPromise<GetProfilesAggregateType<T>>

  /**
   * Group by Profiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfilesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfilesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfilesGroupByArgs['orderBy'] }
      : { orderBy?: ProfilesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfilesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfilesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Profiles model
 */
readonly fields: ProfilesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Profiles.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfilesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  avatarPath<T extends Prisma.Profiles$avatarPathArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Profiles$avatarPathArgs<ExtArgs>>): Prisma.Prisma__FilesOnProfilesClient<runtime.Types.Result.GetResult<Prisma.$FilesOnProfilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Profiles model
 */
export interface ProfilesFieldRefs {
  readonly id: Prisma.FieldRef<"Profiles", 'String'>
  readonly username: Prisma.FieldRef<"Profiles", 'String'>
  readonly userId: Prisma.FieldRef<"Profiles", 'String'>
  readonly phoneNumber: Prisma.FieldRef<"Profiles", 'String'>
  readonly createdAt: Prisma.FieldRef<"Profiles", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Profiles", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Profiles findUnique
 */
export type ProfilesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where: Prisma.ProfilesWhereUniqueInput
}

/**
 * Profiles findUniqueOrThrow
 */
export type ProfilesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where: Prisma.ProfilesWhereUniqueInput
}

/**
 * Profiles findFirst
 */
export type ProfilesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfilesOrderByWithRelationInput | Prisma.ProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfilesScalarFieldEnum | Prisma.ProfilesScalarFieldEnum[]
}

/**
 * Profiles findFirstOrThrow
 */
export type ProfilesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfilesOrderByWithRelationInput | Prisma.ProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Profiles.
   */
  cursor?: Prisma.ProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfilesScalarFieldEnum | Prisma.ProfilesScalarFieldEnum[]
}

/**
 * Profiles findMany
 */
export type ProfilesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * Filter, which Profiles to fetch.
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Profiles to fetch.
   */
  orderBy?: Prisma.ProfilesOrderByWithRelationInput | Prisma.ProfilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Profiles.
   */
  cursor?: Prisma.ProfilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Profiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Profiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Profiles.
   */
  distinct?: Prisma.ProfilesScalarFieldEnum | Prisma.ProfilesScalarFieldEnum[]
}

/**
 * Profiles create
 */
export type ProfilesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * The data needed to create a Profiles.
   */
  data: Prisma.XOR<Prisma.ProfilesCreateInput, Prisma.ProfilesUncheckedCreateInput>
}

/**
 * Profiles createMany
 */
export type ProfilesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfilesCreateManyInput | Prisma.ProfilesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Profiles createManyAndReturn
 */
export type ProfilesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * The data used to create many Profiles.
   */
  data: Prisma.ProfilesCreateManyInput | Prisma.ProfilesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Profiles update
 */
export type ProfilesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * The data needed to update a Profiles.
   */
  data: Prisma.XOR<Prisma.ProfilesUpdateInput, Prisma.ProfilesUncheckedUpdateInput>
  /**
   * Choose, which Profiles to update.
   */
  where: Prisma.ProfilesWhereUniqueInput
}

/**
 * Profiles updateMany
 */
export type ProfilesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfilesUpdateManyMutationInput, Prisma.ProfilesUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
}

/**
 * Profiles updateManyAndReturn
 */
export type ProfilesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * The data used to update Profiles.
   */
  data: Prisma.XOR<Prisma.ProfilesUpdateManyMutationInput, Prisma.ProfilesUncheckedUpdateManyInput>
  /**
   * Filter which Profiles to update
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * Limit how many Profiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Profiles upsert
 */
export type ProfilesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * The filter to search for the Profiles to update in case it exists.
   */
  where: Prisma.ProfilesWhereUniqueInput
  /**
   * In case the Profiles found by the `where` argument doesn't exist, create a new Profiles with this data.
   */
  create: Prisma.XOR<Prisma.ProfilesCreateInput, Prisma.ProfilesUncheckedCreateInput>
  /**
   * In case the Profiles was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfilesUpdateInput, Prisma.ProfilesUncheckedUpdateInput>
}

/**
 * Profiles delete
 */
export type ProfilesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
  /**
   * Filter which Profiles to delete.
   */
  where: Prisma.ProfilesWhereUniqueInput
}

/**
 * Profiles deleteMany
 */
export type ProfilesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Profiles to delete
   */
  where?: Prisma.ProfilesWhereInput
  /**
   * Limit how many Profiles to delete.
   */
  limit?: number
}

/**
 * Profiles.avatarPath
 */
export type Profiles$avatarPathArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesOnProfiles
   */
  select?: Prisma.FilesOnProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilesOnProfiles
   */
  omit?: Prisma.FilesOnProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesOnProfilesInclude<ExtArgs> | null
  where?: Prisma.FilesOnProfilesWhereInput
}

/**
 * Profiles without action
 */
export type ProfilesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Profiles
   */
  select?: Prisma.ProfilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Profiles
   */
  omit?: Prisma.ProfilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfilesInclude<ExtArgs> | null
}
