
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TagsOnPosts` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TagsOnPosts
 * 
 */
export type TagsOnPostsModel = runtime.Types.Result.DefaultSelection<Prisma.$TagsOnPostsPayload>

export type AggregateTagsOnPosts = {
  _count: TagsOnPostsCountAggregateOutputType | null
  _min: TagsOnPostsMinAggregateOutputType | null
  _max: TagsOnPostsMaxAggregateOutputType | null
}

export type TagsOnPostsMinAggregateOutputType = {
  id: string | null
  postId: string | null
  tagId: string | null
  createdAt: Date | null
}

export type TagsOnPostsMaxAggregateOutputType = {
  id: string | null
  postId: string | null
  tagId: string | null
  createdAt: Date | null
}

export type TagsOnPostsCountAggregateOutputType = {
  id: number
  postId: number
  tagId: number
  createdAt: number
  _all: number
}


export type TagsOnPostsMinAggregateInputType = {
  id?: true
  postId?: true
  tagId?: true
  createdAt?: true
}

export type TagsOnPostsMaxAggregateInputType = {
  id?: true
  postId?: true
  tagId?: true
  createdAt?: true
}

export type TagsOnPostsCountAggregateInputType = {
  id?: true
  postId?: true
  tagId?: true
  createdAt?: true
  _all?: true
}

export type TagsOnPostsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagsOnPosts to aggregate.
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnPosts to fetch.
   */
  orderBy?: Prisma.TagsOnPostsOrderByWithRelationInput | Prisma.TagsOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TagsOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TagsOnPosts
  **/
  _count?: true | TagsOnPostsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TagsOnPostsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TagsOnPostsMaxAggregateInputType
}

export type GetTagsOnPostsAggregateType<T extends TagsOnPostsAggregateArgs> = {
      [P in keyof T & keyof AggregateTagsOnPosts]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTagsOnPosts[P]>
    : Prisma.GetScalarType<T[P], AggregateTagsOnPosts[P]>
}




export type TagsOnPostsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagsOnPostsWhereInput
  orderBy?: Prisma.TagsOnPostsOrderByWithAggregationInput | Prisma.TagsOnPostsOrderByWithAggregationInput[]
  by: Prisma.TagsOnPostsScalarFieldEnum[] | Prisma.TagsOnPostsScalarFieldEnum
  having?: Prisma.TagsOnPostsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TagsOnPostsCountAggregateInputType | true
  _min?: TagsOnPostsMinAggregateInputType
  _max?: TagsOnPostsMaxAggregateInputType
}

export type TagsOnPostsGroupByOutputType = {
  id: string
  postId: string
  tagId: string
  createdAt: Date
  _count: TagsOnPostsCountAggregateOutputType | null
  _min: TagsOnPostsMinAggregateOutputType | null
  _max: TagsOnPostsMaxAggregateOutputType | null
}

export type GetTagsOnPostsGroupByPayload<T extends TagsOnPostsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TagsOnPostsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TagsOnPostsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TagsOnPostsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TagsOnPostsGroupByOutputType[P]>
      }
    >
  >



export type TagsOnPostsWhereInput = {
  AND?: Prisma.TagsOnPostsWhereInput | Prisma.TagsOnPostsWhereInput[]
  OR?: Prisma.TagsOnPostsWhereInput[]
  NOT?: Prisma.TagsOnPostsWhereInput | Prisma.TagsOnPostsWhereInput[]
  id?: Prisma.StringFilter<"TagsOnPosts"> | string
  postId?: Prisma.StringFilter<"TagsOnPosts"> | string
  tagId?: Prisma.StringFilter<"TagsOnPosts"> | string
  createdAt?: Prisma.DateTimeFilter<"TagsOnPosts"> | Date | string
  post?: Prisma.XOR<Prisma.PostsScalarRelationFilter, Prisma.PostsWhereInput>
  tag?: Prisma.XOR<Prisma.TagsScalarRelationFilter, Prisma.TagsWhereInput>
}

export type TagsOnPostsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  post?: Prisma.PostsOrderByWithRelationInput
  tag?: Prisma.TagsOrderByWithRelationInput
}

export type TagsOnPostsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TagsOnPostsWhereInput | Prisma.TagsOnPostsWhereInput[]
  OR?: Prisma.TagsOnPostsWhereInput[]
  NOT?: Prisma.TagsOnPostsWhereInput | Prisma.TagsOnPostsWhereInput[]
  postId?: Prisma.StringFilter<"TagsOnPosts"> | string
  tagId?: Prisma.StringFilter<"TagsOnPosts"> | string
  createdAt?: Prisma.DateTimeFilter<"TagsOnPosts"> | Date | string
  post?: Prisma.XOR<Prisma.PostsScalarRelationFilter, Prisma.PostsWhereInput>
  tag?: Prisma.XOR<Prisma.TagsScalarRelationFilter, Prisma.TagsWhereInput>
}, "id">

export type TagsOnPostsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TagsOnPostsCountOrderByAggregateInput
  _max?: Prisma.TagsOnPostsMaxOrderByAggregateInput
  _min?: Prisma.TagsOnPostsMinOrderByAggregateInput
}

export type TagsOnPostsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TagsOnPostsScalarWhereWithAggregatesInput | Prisma.TagsOnPostsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TagsOnPostsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TagsOnPostsScalarWhereWithAggregatesInput | Prisma.TagsOnPostsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TagsOnPosts"> | string
  postId?: Prisma.StringWithAggregatesFilter<"TagsOnPosts"> | string
  tagId?: Prisma.StringWithAggregatesFilter<"TagsOnPosts"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TagsOnPosts"> | Date | string
}

export type TagsOnPostsCreateInput = {
  id?: string
  createdAt?: Date | string
  post: Prisma.PostsCreateNestedOneWithoutTagsInput
  tag: Prisma.TagsCreateNestedOneWithoutPostsInput
}

export type TagsOnPostsUncheckedCreateInput = {
  id?: string
  postId: string
  tagId: string
  createdAt?: Date | string
}

export type TagsOnPostsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  post?: Prisma.PostsUpdateOneRequiredWithoutTagsNestedInput
  tag?: Prisma.TagsUpdateOneRequiredWithoutPostsNestedInput
}

export type TagsOnPostsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnPostsCreateManyInput = {
  id?: string
  postId: string
  tagId: string
  createdAt?: Date | string
}

export type TagsOnPostsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnPostsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnPostsListRelationFilter = {
  every?: Prisma.TagsOnPostsWhereInput
  some?: Prisma.TagsOnPostsWhereInput
  none?: Prisma.TagsOnPostsWhereInput
}

export type TagsOnPostsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TagsOnPostsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TagsOnPostsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TagsOnPostsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TagsOnPostsCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutPostInput, Prisma.TagsOnPostsUncheckedCreateWithoutPostInput> | Prisma.TagsOnPostsCreateWithoutPostInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutPostInput | Prisma.TagsOnPostsCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.TagsOnPostsCreateManyPostInputEnvelope
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
}

export type TagsOnPostsUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutPostInput, Prisma.TagsOnPostsUncheckedCreateWithoutPostInput> | Prisma.TagsOnPostsCreateWithoutPostInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutPostInput | Prisma.TagsOnPostsCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.TagsOnPostsCreateManyPostInputEnvelope
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
}

export type TagsOnPostsUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutPostInput, Prisma.TagsOnPostsUncheckedCreateWithoutPostInput> | Prisma.TagsOnPostsCreateWithoutPostInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutPostInput | Prisma.TagsOnPostsCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutPostInput | Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.TagsOnPostsCreateManyPostInputEnvelope
  set?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  delete?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  update?: Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutPostInput | Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.TagsOnPostsUpdateManyWithWhereWithoutPostInput | Prisma.TagsOnPostsUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.TagsOnPostsScalarWhereInput | Prisma.TagsOnPostsScalarWhereInput[]
}

export type TagsOnPostsUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutPostInput, Prisma.TagsOnPostsUncheckedCreateWithoutPostInput> | Prisma.TagsOnPostsCreateWithoutPostInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutPostInput | Prisma.TagsOnPostsCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutPostInput | Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.TagsOnPostsCreateManyPostInputEnvelope
  set?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  delete?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  update?: Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutPostInput | Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.TagsOnPostsUpdateManyWithWhereWithoutPostInput | Prisma.TagsOnPostsUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.TagsOnPostsScalarWhereInput | Prisma.TagsOnPostsScalarWhereInput[]
}

export type TagsOnPostsCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutTagInput, Prisma.TagsOnPostsUncheckedCreateWithoutTagInput> | Prisma.TagsOnPostsCreateWithoutTagInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutTagInput | Prisma.TagsOnPostsCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagsOnPostsCreateManyTagInputEnvelope
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
}

export type TagsOnPostsUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutTagInput, Prisma.TagsOnPostsUncheckedCreateWithoutTagInput> | Prisma.TagsOnPostsCreateWithoutTagInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutTagInput | Prisma.TagsOnPostsCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagsOnPostsCreateManyTagInputEnvelope
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
}

export type TagsOnPostsUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutTagInput, Prisma.TagsOnPostsUncheckedCreateWithoutTagInput> | Prisma.TagsOnPostsCreateWithoutTagInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutTagInput | Prisma.TagsOnPostsCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutTagInput | Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagsOnPostsCreateManyTagInputEnvelope
  set?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  delete?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  update?: Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutTagInput | Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagsOnPostsUpdateManyWithWhereWithoutTagInput | Prisma.TagsOnPostsUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagsOnPostsScalarWhereInput | Prisma.TagsOnPostsScalarWhereInput[]
}

export type TagsOnPostsUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutTagInput, Prisma.TagsOnPostsUncheckedCreateWithoutTagInput> | Prisma.TagsOnPostsCreateWithoutTagInput[] | Prisma.TagsOnPostsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnPostsCreateOrConnectWithoutTagInput | Prisma.TagsOnPostsCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutTagInput | Prisma.TagsOnPostsUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagsOnPostsCreateManyTagInputEnvelope
  set?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  delete?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  connect?: Prisma.TagsOnPostsWhereUniqueInput | Prisma.TagsOnPostsWhereUniqueInput[]
  update?: Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutTagInput | Prisma.TagsOnPostsUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagsOnPostsUpdateManyWithWhereWithoutTagInput | Prisma.TagsOnPostsUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagsOnPostsScalarWhereInput | Prisma.TagsOnPostsScalarWhereInput[]
}

export type TagsOnPostsCreateWithoutPostInput = {
  id?: string
  createdAt?: Date | string
  tag: Prisma.TagsCreateNestedOneWithoutPostsInput
}

export type TagsOnPostsUncheckedCreateWithoutPostInput = {
  id?: string
  tagId: string
  createdAt?: Date | string
}

export type TagsOnPostsCreateOrConnectWithoutPostInput = {
  where: Prisma.TagsOnPostsWhereUniqueInput
  create: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutPostInput, Prisma.TagsOnPostsUncheckedCreateWithoutPostInput>
}

export type TagsOnPostsCreateManyPostInputEnvelope = {
  data: Prisma.TagsOnPostsCreateManyPostInput | Prisma.TagsOnPostsCreateManyPostInput[]
  skipDuplicates?: boolean
}

export type TagsOnPostsUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.TagsOnPostsWhereUniqueInput
  update: Prisma.XOR<Prisma.TagsOnPostsUpdateWithoutPostInput, Prisma.TagsOnPostsUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutPostInput, Prisma.TagsOnPostsUncheckedCreateWithoutPostInput>
}

export type TagsOnPostsUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.TagsOnPostsWhereUniqueInput
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateWithoutPostInput, Prisma.TagsOnPostsUncheckedUpdateWithoutPostInput>
}

export type TagsOnPostsUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.TagsOnPostsScalarWhereInput
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateManyMutationInput, Prisma.TagsOnPostsUncheckedUpdateManyWithoutPostInput>
}

export type TagsOnPostsScalarWhereInput = {
  AND?: Prisma.TagsOnPostsScalarWhereInput | Prisma.TagsOnPostsScalarWhereInput[]
  OR?: Prisma.TagsOnPostsScalarWhereInput[]
  NOT?: Prisma.TagsOnPostsScalarWhereInput | Prisma.TagsOnPostsScalarWhereInput[]
  id?: Prisma.StringFilter<"TagsOnPosts"> | string
  postId?: Prisma.StringFilter<"TagsOnPosts"> | string
  tagId?: Prisma.StringFilter<"TagsOnPosts"> | string
  createdAt?: Prisma.DateTimeFilter<"TagsOnPosts"> | Date | string
}

export type TagsOnPostsCreateWithoutTagInput = {
  id?: string
  createdAt?: Date | string
  post: Prisma.PostsCreateNestedOneWithoutTagsInput
}

export type TagsOnPostsUncheckedCreateWithoutTagInput = {
  id?: string
  postId: string
  createdAt?: Date | string
}

export type TagsOnPostsCreateOrConnectWithoutTagInput = {
  where: Prisma.TagsOnPostsWhereUniqueInput
  create: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutTagInput, Prisma.TagsOnPostsUncheckedCreateWithoutTagInput>
}

export type TagsOnPostsCreateManyTagInputEnvelope = {
  data: Prisma.TagsOnPostsCreateManyTagInput | Prisma.TagsOnPostsCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type TagsOnPostsUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagsOnPostsWhereUniqueInput
  update: Prisma.XOR<Prisma.TagsOnPostsUpdateWithoutTagInput, Prisma.TagsOnPostsUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.TagsOnPostsCreateWithoutTagInput, Prisma.TagsOnPostsUncheckedCreateWithoutTagInput>
}

export type TagsOnPostsUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagsOnPostsWhereUniqueInput
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateWithoutTagInput, Prisma.TagsOnPostsUncheckedUpdateWithoutTagInput>
}

export type TagsOnPostsUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.TagsOnPostsScalarWhereInput
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateManyMutationInput, Prisma.TagsOnPostsUncheckedUpdateManyWithoutTagInput>
}

export type TagsOnPostsCreateManyPostInput = {
  id?: string
  tagId: string
  createdAt?: Date | string
}

export type TagsOnPostsUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tag?: Prisma.TagsUpdateOneRequiredWithoutPostsNestedInput
}

export type TagsOnPostsUncheckedUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnPostsUncheckedUpdateManyWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnPostsCreateManyTagInput = {
  id?: string
  postId: string
  createdAt?: Date | string
}

export type TagsOnPostsUpdateWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  post?: Prisma.PostsUpdateOneRequiredWithoutTagsNestedInput
}

export type TagsOnPostsUncheckedUpdateWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagsOnPostsUncheckedUpdateManyWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TagsOnPostsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postId?: boolean
  tagId?: boolean
  createdAt?: boolean
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnPosts"]>

export type TagsOnPostsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postId?: boolean
  tagId?: boolean
  createdAt?: boolean
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnPosts"]>

export type TagsOnPostsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  postId?: boolean
  tagId?: boolean
  createdAt?: boolean
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnPosts"]>

export type TagsOnPostsSelectScalar = {
  id?: boolean
  postId?: boolean
  tagId?: boolean
  createdAt?: boolean
}

export type TagsOnPostsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "postId" | "tagId" | "createdAt", ExtArgs["result"]["tagsOnPosts"]>
export type TagsOnPostsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
}
export type TagsOnPostsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
}
export type TagsOnPostsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.PostsDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
}

export type $TagsOnPostsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TagsOnPosts"
  objects: {
    post: Prisma.$PostsPayload<ExtArgs>
    tag: Prisma.$TagsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    postId: string
    tagId: string
    createdAt: Date
  }, ExtArgs["result"]["tagsOnPosts"]>
  composites: {}
}

export type TagsOnPostsGetPayload<S extends boolean | null | undefined | TagsOnPostsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload, S>

export type TagsOnPostsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TagsOnPostsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TagsOnPostsCountAggregateInputType | true
  }

export interface TagsOnPostsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TagsOnPosts'], meta: { name: 'TagsOnPosts' } }
  /**
   * Find zero or one TagsOnPosts that matches the filter.
   * @param {TagsOnPostsFindUniqueArgs} args - Arguments to find a TagsOnPosts
   * @example
   * // Get one TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TagsOnPostsFindUniqueArgs>(args: Prisma.SelectSubset<T, TagsOnPostsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TagsOnPosts that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TagsOnPostsFindUniqueOrThrowArgs} args - Arguments to find a TagsOnPosts
   * @example
   * // Get one TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TagsOnPostsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TagsOnPostsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagsOnPosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsFindFirstArgs} args - Arguments to find a TagsOnPosts
   * @example
   * // Get one TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TagsOnPostsFindFirstArgs>(args?: Prisma.SelectSubset<T, TagsOnPostsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagsOnPosts that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsFindFirstOrThrowArgs} args - Arguments to find a TagsOnPosts
   * @example
   * // Get one TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TagsOnPostsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TagsOnPostsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TagsOnPosts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.findMany()
   * 
   * // Get first 10 TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tagsOnPostsWithIdOnly = await prisma.tagsOnPosts.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TagsOnPostsFindManyArgs>(args?: Prisma.SelectSubset<T, TagsOnPostsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TagsOnPosts.
   * @param {TagsOnPostsCreateArgs} args - Arguments to create a TagsOnPosts.
   * @example
   * // Create one TagsOnPosts
   * const TagsOnPosts = await prisma.tagsOnPosts.create({
   *   data: {
   *     // ... data to create a TagsOnPosts
   *   }
   * })
   * 
   */
  create<T extends TagsOnPostsCreateArgs>(args: Prisma.SelectSubset<T, TagsOnPostsCreateArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TagsOnPosts.
   * @param {TagsOnPostsCreateManyArgs} args - Arguments to create many TagsOnPosts.
   * @example
   * // Create many TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TagsOnPostsCreateManyArgs>(args?: Prisma.SelectSubset<T, TagsOnPostsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TagsOnPosts and returns the data saved in the database.
   * @param {TagsOnPostsCreateManyAndReturnArgs} args - Arguments to create many TagsOnPosts.
   * @example
   * // Create many TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TagsOnPosts and only return the `id`
   * const tagsOnPostsWithIdOnly = await prisma.tagsOnPosts.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TagsOnPostsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TagsOnPostsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TagsOnPosts.
   * @param {TagsOnPostsDeleteArgs} args - Arguments to delete one TagsOnPosts.
   * @example
   * // Delete one TagsOnPosts
   * const TagsOnPosts = await prisma.tagsOnPosts.delete({
   *   where: {
   *     // ... filter to delete one TagsOnPosts
   *   }
   * })
   * 
   */
  delete<T extends TagsOnPostsDeleteArgs>(args: Prisma.SelectSubset<T, TagsOnPostsDeleteArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TagsOnPosts.
   * @param {TagsOnPostsUpdateArgs} args - Arguments to update one TagsOnPosts.
   * @example
   * // Update one TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TagsOnPostsUpdateArgs>(args: Prisma.SelectSubset<T, TagsOnPostsUpdateArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TagsOnPosts.
   * @param {TagsOnPostsDeleteManyArgs} args - Arguments to filter TagsOnPosts to delete.
   * @example
   * // Delete a few TagsOnPosts
   * const { count } = await prisma.tagsOnPosts.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TagsOnPostsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TagsOnPostsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagsOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TagsOnPostsUpdateManyArgs>(args: Prisma.SelectSubset<T, TagsOnPostsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagsOnPosts and returns the data updated in the database.
   * @param {TagsOnPostsUpdateManyAndReturnArgs} args - Arguments to update many TagsOnPosts.
   * @example
   * // Update many TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TagsOnPosts and only return the `id`
   * const tagsOnPostsWithIdOnly = await prisma.tagsOnPosts.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TagsOnPostsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TagsOnPostsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TagsOnPosts.
   * @param {TagsOnPostsUpsertArgs} args - Arguments to update or create a TagsOnPosts.
   * @example
   * // Update or create a TagsOnPosts
   * const tagsOnPosts = await prisma.tagsOnPosts.upsert({
   *   create: {
   *     // ... data to create a TagsOnPosts
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TagsOnPosts we want to update
   *   }
   * })
   */
  upsert<T extends TagsOnPostsUpsertArgs>(args: Prisma.SelectSubset<T, TagsOnPostsUpsertArgs<ExtArgs>>): Prisma.Prisma__TagsOnPostsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnPostsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TagsOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsCountArgs} args - Arguments to filter TagsOnPosts to count.
   * @example
   * // Count the number of TagsOnPosts
   * const count = await prisma.tagsOnPosts.count({
   *   where: {
   *     // ... the filter for the TagsOnPosts we want to count
   *   }
   * })
  **/
  count<T extends TagsOnPostsCountArgs>(
    args?: Prisma.Subset<T, TagsOnPostsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TagsOnPostsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TagsOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TagsOnPostsAggregateArgs>(args: Prisma.Subset<T, TagsOnPostsAggregateArgs>): Prisma.PrismaPromise<GetTagsOnPostsAggregateType<T>>

  /**
   * Group by TagsOnPosts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnPostsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TagsOnPostsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TagsOnPostsGroupByArgs['orderBy'] }
      : { orderBy?: TagsOnPostsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TagsOnPostsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTagsOnPostsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TagsOnPosts model
 */
readonly fields: TagsOnPostsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TagsOnPosts.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TagsOnPostsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  post<T extends Prisma.PostsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostsDefaultArgs<ExtArgs>>): Prisma.Prisma__PostsClient<runtime.Types.Result.GetResult<Prisma.$PostsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.TagsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagsDefaultArgs<ExtArgs>>): Prisma.Prisma__TagsClient<runtime.Types.Result.GetResult<Prisma.$TagsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TagsOnPosts model
 */
export interface TagsOnPostsFieldRefs {
  readonly id: Prisma.FieldRef<"TagsOnPosts", 'String'>
  readonly postId: Prisma.FieldRef<"TagsOnPosts", 'String'>
  readonly tagId: Prisma.FieldRef<"TagsOnPosts", 'String'>
  readonly createdAt: Prisma.FieldRef<"TagsOnPosts", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TagsOnPosts findUnique
 */
export type TagsOnPostsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnPosts to fetch.
   */
  where: Prisma.TagsOnPostsWhereUniqueInput
}

/**
 * TagsOnPosts findUniqueOrThrow
 */
export type TagsOnPostsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnPosts to fetch.
   */
  where: Prisma.TagsOnPostsWhereUniqueInput
}

/**
 * TagsOnPosts findFirst
 */
export type TagsOnPostsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnPosts to fetch.
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnPosts to fetch.
   */
  orderBy?: Prisma.TagsOnPostsOrderByWithRelationInput | Prisma.TagsOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagsOnPosts.
   */
  cursor?: Prisma.TagsOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnPosts.
   */
  distinct?: Prisma.TagsOnPostsScalarFieldEnum | Prisma.TagsOnPostsScalarFieldEnum[]
}

/**
 * TagsOnPosts findFirstOrThrow
 */
export type TagsOnPostsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnPosts to fetch.
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnPosts to fetch.
   */
  orderBy?: Prisma.TagsOnPostsOrderByWithRelationInput | Prisma.TagsOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagsOnPosts.
   */
  cursor?: Prisma.TagsOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnPosts.
   */
  distinct?: Prisma.TagsOnPostsScalarFieldEnum | Prisma.TagsOnPostsScalarFieldEnum[]
}

/**
 * TagsOnPosts findMany
 */
export type TagsOnPostsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnPosts to fetch.
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnPosts to fetch.
   */
  orderBy?: Prisma.TagsOnPostsOrderByWithRelationInput | Prisma.TagsOnPostsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TagsOnPosts.
   */
  cursor?: Prisma.TagsOnPostsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnPosts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnPosts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnPosts.
   */
  distinct?: Prisma.TagsOnPostsScalarFieldEnum | Prisma.TagsOnPostsScalarFieldEnum[]
}

/**
 * TagsOnPosts create
 */
export type TagsOnPostsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * The data needed to create a TagsOnPosts.
   */
  data: Prisma.XOR<Prisma.TagsOnPostsCreateInput, Prisma.TagsOnPostsUncheckedCreateInput>
}

/**
 * TagsOnPosts createMany
 */
export type TagsOnPostsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TagsOnPosts.
   */
  data: Prisma.TagsOnPostsCreateManyInput | Prisma.TagsOnPostsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TagsOnPosts createManyAndReturn
 */
export type TagsOnPostsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * The data used to create many TagsOnPosts.
   */
  data: Prisma.TagsOnPostsCreateManyInput | Prisma.TagsOnPostsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TagsOnPosts update
 */
export type TagsOnPostsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * The data needed to update a TagsOnPosts.
   */
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateInput, Prisma.TagsOnPostsUncheckedUpdateInput>
  /**
   * Choose, which TagsOnPosts to update.
   */
  where: Prisma.TagsOnPostsWhereUniqueInput
}

/**
 * TagsOnPosts updateMany
 */
export type TagsOnPostsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TagsOnPosts.
   */
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateManyMutationInput, Prisma.TagsOnPostsUncheckedUpdateManyInput>
  /**
   * Filter which TagsOnPosts to update
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * Limit how many TagsOnPosts to update.
   */
  limit?: number
}

/**
 * TagsOnPosts updateManyAndReturn
 */
export type TagsOnPostsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * The data used to update TagsOnPosts.
   */
  data: Prisma.XOR<Prisma.TagsOnPostsUpdateManyMutationInput, Prisma.TagsOnPostsUncheckedUpdateManyInput>
  /**
   * Filter which TagsOnPosts to update
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * Limit how many TagsOnPosts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TagsOnPosts upsert
 */
export type TagsOnPostsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * The filter to search for the TagsOnPosts to update in case it exists.
   */
  where: Prisma.TagsOnPostsWhereUniqueInput
  /**
   * In case the TagsOnPosts found by the `where` argument doesn't exist, create a new TagsOnPosts with this data.
   */
  create: Prisma.XOR<Prisma.TagsOnPostsCreateInput, Prisma.TagsOnPostsUncheckedCreateInput>
  /**
   * In case the TagsOnPosts was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TagsOnPostsUpdateInput, Prisma.TagsOnPostsUncheckedUpdateInput>
}

/**
 * TagsOnPosts delete
 */
export type TagsOnPostsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
  /**
   * Filter which TagsOnPosts to delete.
   */
  where: Prisma.TagsOnPostsWhereUniqueInput
}

/**
 * TagsOnPosts deleteMany
 */
export type TagsOnPostsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagsOnPosts to delete
   */
  where?: Prisma.TagsOnPostsWhereInput
  /**
   * Limit how many TagsOnPosts to delete.
   */
  limit?: number
}

/**
 * TagsOnPosts without action
 */
export type TagsOnPostsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnPosts
   */
  select?: Prisma.TagsOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnPosts
   */
  omit?: Prisma.TagsOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnPostsInclude<ExtArgs> | null
}
