
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Views` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Views
 * 
 */
export type ViewsModel = runtime.Types.Result.DefaultSelection<Prisma.$ViewsPayload>

export type AggregateViews = {
  _count: ViewsCountAggregateOutputType | null
  _avg: ViewsAvgAggregateOutputType | null
  _sum: ViewsSumAggregateOutputType | null
  _min: ViewsMinAggregateOutputType | null
  _max: ViewsMaxAggregateOutputType | null
}

export type ViewsAvgAggregateOutputType = {
  expiredAt: number | null
}

export type ViewsSumAggregateOutputType = {
  expiredAt: number | null
}

export type ViewsMinAggregateOutputType = {
  id: string | null
  ip_address: string | null
  userAgent: string | null
  createdAt: Date | null
  expiredAt: number | null
}

export type ViewsMaxAggregateOutputType = {
  id: string | null
  ip_address: string | null
  userAgent: string | null
  createdAt: Date | null
  expiredAt: number | null
}

export type ViewsCountAggregateOutputType = {
  id: number
  ip_address: number
  userAgent: number
  createdAt: number
  expiredAt: number
  _all: number
}


export type ViewsAvgAggregateInputType = {
  expiredAt?: true
}

export type ViewsSumAggregateInputType = {
  expiredAt?: true
}

export type ViewsMinAggregateInputType = {
  id?: true
  ip_address?: true
  userAgent?: true
  createdAt?: true
  expiredAt?: true
}

export type ViewsMaxAggregateInputType = {
  id?: true
  ip_address?: true
  userAgent?: true
  createdAt?: true
  expiredAt?: true
}

export type ViewsCountAggregateInputType = {
  id?: true
  ip_address?: true
  userAgent?: true
  createdAt?: true
  expiredAt?: true
  _all?: true
}

export type ViewsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Views to aggregate.
   */
  where?: Prisma.ViewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Views to fetch.
   */
  orderBy?: Prisma.ViewsOrderByWithRelationInput | Prisma.ViewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ViewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Views
  **/
  _count?: true | ViewsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ViewsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ViewsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ViewsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ViewsMaxAggregateInputType
}

export type GetViewsAggregateType<T extends ViewsAggregateArgs> = {
      [P in keyof T & keyof AggregateViews]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateViews[P]>
    : Prisma.GetScalarType<T[P], AggregateViews[P]>
}




export type ViewsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ViewsWhereInput
  orderBy?: Prisma.ViewsOrderByWithAggregationInput | Prisma.ViewsOrderByWithAggregationInput[]
  by: Prisma.ViewsScalarFieldEnum[] | Prisma.ViewsScalarFieldEnum
  having?: Prisma.ViewsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ViewsCountAggregateInputType | true
  _avg?: ViewsAvgAggregateInputType
  _sum?: ViewsSumAggregateInputType
  _min?: ViewsMinAggregateInputType
  _max?: ViewsMaxAggregateInputType
}

export type ViewsGroupByOutputType = {
  id: string
  ip_address: string
  userAgent: string
  createdAt: Date
  expiredAt: number
  _count: ViewsCountAggregateOutputType | null
  _avg: ViewsAvgAggregateOutputType | null
  _sum: ViewsSumAggregateOutputType | null
  _min: ViewsMinAggregateOutputType | null
  _max: ViewsMaxAggregateOutputType | null
}

export type GetViewsGroupByPayload<T extends ViewsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ViewsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ViewsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ViewsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ViewsGroupByOutputType[P]>
      }
    >
  >



export type ViewsWhereInput = {
  AND?: Prisma.ViewsWhereInput | Prisma.ViewsWhereInput[]
  OR?: Prisma.ViewsWhereInput[]
  NOT?: Prisma.ViewsWhereInput | Prisma.ViewsWhereInput[]
  id?: Prisma.StringFilter<"Views"> | string
  ip_address?: Prisma.StringFilter<"Views"> | string
  userAgent?: Prisma.StringFilter<"Views"> | string
  createdAt?: Prisma.DateTimeFilter<"Views"> | Date | string
  expiredAt?: Prisma.IntFilter<"Views"> | number
  post?: Prisma.ViewOnPostsListRelationFilter
}

export type ViewsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  post?: Prisma.ViewOnPostsOrderByRelationAggregateInput
}

export type ViewsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ViewsWhereInput | Prisma.ViewsWhereInput[]
  OR?: Prisma.ViewsWhereInput[]
  NOT?: Prisma.ViewsWhereInput | Prisma.ViewsWhereInput[]
  ip_address?: Prisma.StringFilter<"Views"> | string
  userAgent?: Prisma.StringFilter<"Views"> | string
  createdAt?: Prisma.DateTimeFilter<"Views"> | Date | string
  expiredAt?: Prisma.IntFilter<"Views"> | number
  post?: Prisma.ViewOnPostsListRelationFilter
}, "id">

export type ViewsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  _count?: Prisma.ViewsCountOrderByAggregateInput
  _avg?: Prisma.ViewsAvgOrderByAggregateInput
  _max?: Prisma.ViewsMaxOrderByAggregateInput
  _min?: Prisma.ViewsMinOrderByAggregateInput
  _sum?: Prisma.ViewsSumOrderByAggregateInput
}

export type ViewsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ViewsScalarWhereWithAggregatesInput | Prisma.ViewsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ViewsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ViewsScalarWhereWithAggregatesInput | Prisma.ViewsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Views"> | string
  ip_address?: Prisma.StringWithAggregatesFilter<"Views"> | string
  userAgent?: Prisma.StringWithAggregatesFilter<"Views"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Views"> | Date | string
  expiredAt?: Prisma.IntWithAggregatesFilter<"Views"> | number
}

export type ViewsCreateInput = {
  id?: string
  ip_address: string
  userAgent: string
  createdAt?: Date | string
  expiredAt: number
  post?: Prisma.ViewOnPostsCreateNestedManyWithoutViewInput
}

export type ViewsUncheckedCreateInput = {
  id?: string
  ip_address: string
  userAgent: string
  createdAt?: Date | string
  expiredAt: number
  post?: Prisma.ViewOnPostsUncheckedCreateNestedManyWithoutViewInput
}

export type ViewsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.StringFieldUpdateOperationsInput | string
  userAgent?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.IntFieldUpdateOperationsInput | number
  post?: Prisma.ViewOnPostsUpdateManyWithoutViewNestedInput
}

export type ViewsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.StringFieldUpdateOperationsInput | string
  userAgent?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.IntFieldUpdateOperationsInput | number
  post?: Prisma.ViewOnPostsUncheckedUpdateManyWithoutViewNestedInput
}

export type ViewsCreateManyInput = {
  id?: string
  ip_address: string
  userAgent: string
  createdAt?: Date | string
  expiredAt: number
}

export type ViewsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.StringFieldUpdateOperationsInput | string
  userAgent?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ViewsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.StringFieldUpdateOperationsInput | string
  userAgent?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ViewsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
}

export type ViewsAvgOrderByAggregateInput = {
  expiredAt?: Prisma.SortOrder
}

export type ViewsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
}

export type ViewsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ip_address?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
}

export type ViewsSumOrderByAggregateInput = {
  expiredAt?: Prisma.SortOrder
}

export type ViewsScalarRelationFilter = {
  is?: Prisma.ViewsWhereInput
  isNot?: Prisma.ViewsWhereInput
}

export type ViewsCreateNestedOneWithoutPostInput = {
  create?: Prisma.XOR<Prisma.ViewsCreateWithoutPostInput, Prisma.ViewsUncheckedCreateWithoutPostInput>
  connectOrCreate?: Prisma.ViewsCreateOrConnectWithoutPostInput
  connect?: Prisma.ViewsWhereUniqueInput
}

export type ViewsUpdateOneRequiredWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.ViewsCreateWithoutPostInput, Prisma.ViewsUncheckedCreateWithoutPostInput>
  connectOrCreate?: Prisma.ViewsCreateOrConnectWithoutPostInput
  upsert?: Prisma.ViewsUpsertWithoutPostInput
  connect?: Prisma.ViewsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ViewsUpdateToOneWithWhereWithoutPostInput, Prisma.ViewsUpdateWithoutPostInput>, Prisma.ViewsUncheckedUpdateWithoutPostInput>
}

export type ViewsCreateWithoutPostInput = {
  id?: string
  ip_address: string
  userAgent: string
  createdAt?: Date | string
  expiredAt: number
}

export type ViewsUncheckedCreateWithoutPostInput = {
  id?: string
  ip_address: string
  userAgent: string
  createdAt?: Date | string
  expiredAt: number
}

export type ViewsCreateOrConnectWithoutPostInput = {
  where: Prisma.ViewsWhereUniqueInput
  create: Prisma.XOR<Prisma.ViewsCreateWithoutPostInput, Prisma.ViewsUncheckedCreateWithoutPostInput>
}

export type ViewsUpsertWithoutPostInput = {
  update: Prisma.XOR<Prisma.ViewsUpdateWithoutPostInput, Prisma.ViewsUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.ViewsCreateWithoutPostInput, Prisma.ViewsUncheckedCreateWithoutPostInput>
  where?: Prisma.ViewsWhereInput
}

export type ViewsUpdateToOneWithWhereWithoutPostInput = {
  where?: Prisma.ViewsWhereInput
  data: Prisma.XOR<Prisma.ViewsUpdateWithoutPostInput, Prisma.ViewsUncheckedUpdateWithoutPostInput>
}

export type ViewsUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.StringFieldUpdateOperationsInput | string
  userAgent?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ViewsUncheckedUpdateWithoutPostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ip_address?: Prisma.StringFieldUpdateOperationsInput | string
  userAgent?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ViewsCountOutputType
 */

export type ViewsCountOutputType = {
  post: number
}

export type ViewsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | ViewsCountOutputTypeCountPostArgs
}

/**
 * ViewsCountOutputType without action
 */
export type ViewsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewsCountOutputType
   */
  select?: Prisma.ViewsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ViewsCountOutputType without action
 */
export type ViewsCountOutputTypeCountPostArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ViewOnPostsWhereInput
}


export type ViewsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ip_address?: boolean
  userAgent?: boolean
  createdAt?: boolean
  expiredAt?: boolean
  post?: boolean | Prisma.Views$postArgs<ExtArgs>
  _count?: boolean | Prisma.ViewsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["views"]>

export type ViewsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ip_address?: boolean
  userAgent?: boolean
  createdAt?: boolean
  expiredAt?: boolean
}, ExtArgs["result"]["views"]>

export type ViewsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ip_address?: boolean
  userAgent?: boolean
  createdAt?: boolean
  expiredAt?: boolean
}, ExtArgs["result"]["views"]>

export type ViewsSelectScalar = {
  id?: boolean
  ip_address?: boolean
  userAgent?: boolean
  createdAt?: boolean
  expiredAt?: boolean
}

export type ViewsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ip_address" | "userAgent" | "createdAt" | "expiredAt", ExtArgs["result"]["views"]>
export type ViewsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  post?: boolean | Prisma.Views$postArgs<ExtArgs>
  _count?: boolean | Prisma.ViewsCountOutputTypeDefaultArgs<ExtArgs>
}
export type ViewsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ViewsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ViewsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Views"
  objects: {
    post: Prisma.$ViewOnPostsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ip_address: string
    userAgent: string
    createdAt: Date
    expiredAt: number
  }, ExtArgs["result"]["views"]>
  composites: {}
}

export type ViewsGetPayload<S extends boolean | null | undefined | ViewsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ViewsPayload, S>

export type ViewsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ViewsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ViewsCountAggregateInputType | true
  }

export interface ViewsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Views'], meta: { name: 'Views' } }
  /**
   * Find zero or one Views that matches the filter.
   * @param {ViewsFindUniqueArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ViewsFindUniqueArgs>(args: Prisma.SelectSubset<T, ViewsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Views that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ViewsFindUniqueOrThrowArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ViewsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ViewsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Views that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsFindFirstArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ViewsFindFirstArgs>(args?: Prisma.SelectSubset<T, ViewsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Views that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsFindFirstOrThrowArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ViewsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ViewsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Views that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Views
   * const views = await prisma.views.findMany()
   * 
   * // Get first 10 Views
   * const views = await prisma.views.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const viewsWithIdOnly = await prisma.views.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ViewsFindManyArgs>(args?: Prisma.SelectSubset<T, ViewsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Views.
   * @param {ViewsCreateArgs} args - Arguments to create a Views.
   * @example
   * // Create one Views
   * const Views = await prisma.views.create({
   *   data: {
   *     // ... data to create a Views
   *   }
   * })
   * 
   */
  create<T extends ViewsCreateArgs>(args: Prisma.SelectSubset<T, ViewsCreateArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Views.
   * @param {ViewsCreateManyArgs} args - Arguments to create many Views.
   * @example
   * // Create many Views
   * const views = await prisma.views.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ViewsCreateManyArgs>(args?: Prisma.SelectSubset<T, ViewsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Views and returns the data saved in the database.
   * @param {ViewsCreateManyAndReturnArgs} args - Arguments to create many Views.
   * @example
   * // Create many Views
   * const views = await prisma.views.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Views and only return the `id`
   * const viewsWithIdOnly = await prisma.views.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ViewsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ViewsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Views.
   * @param {ViewsDeleteArgs} args - Arguments to delete one Views.
   * @example
   * // Delete one Views
   * const Views = await prisma.views.delete({
   *   where: {
   *     // ... filter to delete one Views
   *   }
   * })
   * 
   */
  delete<T extends ViewsDeleteArgs>(args: Prisma.SelectSubset<T, ViewsDeleteArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Views.
   * @param {ViewsUpdateArgs} args - Arguments to update one Views.
   * @example
   * // Update one Views
   * const views = await prisma.views.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ViewsUpdateArgs>(args: Prisma.SelectSubset<T, ViewsUpdateArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Views.
   * @param {ViewsDeleteManyArgs} args - Arguments to filter Views to delete.
   * @example
   * // Delete a few Views
   * const { count } = await prisma.views.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ViewsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ViewsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Views
   * const views = await prisma.views.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ViewsUpdateManyArgs>(args: Prisma.SelectSubset<T, ViewsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Views and returns the data updated in the database.
   * @param {ViewsUpdateManyAndReturnArgs} args - Arguments to update many Views.
   * @example
   * // Update many Views
   * const views = await prisma.views.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Views and only return the `id`
   * const viewsWithIdOnly = await prisma.views.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ViewsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ViewsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Views.
   * @param {ViewsUpsertArgs} args - Arguments to update or create a Views.
   * @example
   * // Update or create a Views
   * const views = await prisma.views.upsert({
   *   create: {
   *     // ... data to create a Views
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Views we want to update
   *   }
   * })
   */
  upsert<T extends ViewsUpsertArgs>(args: Prisma.SelectSubset<T, ViewsUpsertArgs<ExtArgs>>): Prisma.Prisma__ViewsClient<runtime.Types.Result.GetResult<Prisma.$ViewsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsCountArgs} args - Arguments to filter Views to count.
   * @example
   * // Count the number of Views
   * const count = await prisma.views.count({
   *   where: {
   *     // ... the filter for the Views we want to count
   *   }
   * })
  **/
  count<T extends ViewsCountArgs>(
    args?: Prisma.Subset<T, ViewsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ViewsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ViewsAggregateArgs>(args: Prisma.Subset<T, ViewsAggregateArgs>): Prisma.PrismaPromise<GetViewsAggregateType<T>>

  /**
   * Group by Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ViewsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ViewsGroupByArgs['orderBy'] }
      : { orderBy?: ViewsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ViewsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetViewsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Views model
 */
readonly fields: ViewsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Views.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ViewsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  post<T extends Prisma.Views$postArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Views$postArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewOnPostsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Views model
 */
export interface ViewsFieldRefs {
  readonly id: Prisma.FieldRef<"Views", 'String'>
  readonly ip_address: Prisma.FieldRef<"Views", 'String'>
  readonly userAgent: Prisma.FieldRef<"Views", 'String'>
  readonly createdAt: Prisma.FieldRef<"Views", 'DateTime'>
  readonly expiredAt: Prisma.FieldRef<"Views", 'Int'>
}
    

// Custom InputTypes
/**
 * Views findUnique
 */
export type ViewsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * Filter, which Views to fetch.
   */
  where: Prisma.ViewsWhereUniqueInput
}

/**
 * Views findUniqueOrThrow
 */
export type ViewsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * Filter, which Views to fetch.
   */
  where: Prisma.ViewsWhereUniqueInput
}

/**
 * Views findFirst
 */
export type ViewsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * Filter, which Views to fetch.
   */
  where?: Prisma.ViewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Views to fetch.
   */
  orderBy?: Prisma.ViewsOrderByWithRelationInput | Prisma.ViewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Views.
   */
  cursor?: Prisma.ViewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Views.
   */
  distinct?: Prisma.ViewsScalarFieldEnum | Prisma.ViewsScalarFieldEnum[]
}

/**
 * Views findFirstOrThrow
 */
export type ViewsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * Filter, which Views to fetch.
   */
  where?: Prisma.ViewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Views to fetch.
   */
  orderBy?: Prisma.ViewsOrderByWithRelationInput | Prisma.ViewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Views.
   */
  cursor?: Prisma.ViewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Views.
   */
  distinct?: Prisma.ViewsScalarFieldEnum | Prisma.ViewsScalarFieldEnum[]
}

/**
 * Views findMany
 */
export type ViewsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * Filter, which Views to fetch.
   */
  where?: Prisma.ViewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Views to fetch.
   */
  orderBy?: Prisma.ViewsOrderByWithRelationInput | Prisma.ViewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Views.
   */
  cursor?: Prisma.ViewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Views.
   */
  distinct?: Prisma.ViewsScalarFieldEnum | Prisma.ViewsScalarFieldEnum[]
}

/**
 * Views create
 */
export type ViewsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * The data needed to create a Views.
   */
  data: Prisma.XOR<Prisma.ViewsCreateInput, Prisma.ViewsUncheckedCreateInput>
}

/**
 * Views createMany
 */
export type ViewsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Views.
   */
  data: Prisma.ViewsCreateManyInput | Prisma.ViewsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Views createManyAndReturn
 */
export type ViewsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * The data used to create many Views.
   */
  data: Prisma.ViewsCreateManyInput | Prisma.ViewsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Views update
 */
export type ViewsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * The data needed to update a Views.
   */
  data: Prisma.XOR<Prisma.ViewsUpdateInput, Prisma.ViewsUncheckedUpdateInput>
  /**
   * Choose, which Views to update.
   */
  where: Prisma.ViewsWhereUniqueInput
}

/**
 * Views updateMany
 */
export type ViewsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Views.
   */
  data: Prisma.XOR<Prisma.ViewsUpdateManyMutationInput, Prisma.ViewsUncheckedUpdateManyInput>
  /**
   * Filter which Views to update
   */
  where?: Prisma.ViewsWhereInput
  /**
   * Limit how many Views to update.
   */
  limit?: number
}

/**
 * Views updateManyAndReturn
 */
export type ViewsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * The data used to update Views.
   */
  data: Prisma.XOR<Prisma.ViewsUpdateManyMutationInput, Prisma.ViewsUncheckedUpdateManyInput>
  /**
   * Filter which Views to update
   */
  where?: Prisma.ViewsWhereInput
  /**
   * Limit how many Views to update.
   */
  limit?: number
}

/**
 * Views upsert
 */
export type ViewsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * The filter to search for the Views to update in case it exists.
   */
  where: Prisma.ViewsWhereUniqueInput
  /**
   * In case the Views found by the `where` argument doesn't exist, create a new Views with this data.
   */
  create: Prisma.XOR<Prisma.ViewsCreateInput, Prisma.ViewsUncheckedCreateInput>
  /**
   * In case the Views was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ViewsUpdateInput, Prisma.ViewsUncheckedUpdateInput>
}

/**
 * Views delete
 */
export type ViewsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
  /**
   * Filter which Views to delete.
   */
  where: Prisma.ViewsWhereUniqueInput
}

/**
 * Views deleteMany
 */
export type ViewsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Views to delete
   */
  where?: Prisma.ViewsWhereInput
  /**
   * Limit how many Views to delete.
   */
  limit?: number
}

/**
 * Views.post
 */
export type Views$postArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewOnPosts
   */
  select?: Prisma.ViewOnPostsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewOnPosts
   */
  omit?: Prisma.ViewOnPostsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewOnPostsInclude<ExtArgs> | null
  where?: Prisma.ViewOnPostsWhereInput
  orderBy?: Prisma.ViewOnPostsOrderByWithRelationInput | Prisma.ViewOnPostsOrderByWithRelationInput[]
  cursor?: Prisma.ViewOnPostsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ViewOnPostsScalarFieldEnum | Prisma.ViewOnPostsScalarFieldEnum[]
}

/**
 * Views without action
 */
export type ViewsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Views
   */
  select?: Prisma.ViewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Views
   */
  omit?: Prisma.ViewsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewsInclude<ExtArgs> | null
}
